(lang dune 3.16)
(generate_opam_files true)
(name math-coding)
(version 3.0-alpha)
(source (github 11111000000/math-coding))
(license Apache-2.0)
(authors "Petr Kosov <p.b.kosov@yandex.ru>")
(maintainers "Petr Kosov <p.b.kosov@yandex.ru>")
(homepage https://github.com/11111000000/math-coding)
(documentation https://11111000000.github.io/math-coding/)
(depends (ocaml (>= 5.0)) (dune (>= 3.16)))
