(* core/render.ml -- site generation for math-coding v2.0-Y.

   Generates a complete static site under dist/:
     - index.html         front page (hero, packet grid, mermaid)
     - manifesto.html     LaTeX rendered via pandoc with mathjax
     - manifesto-narrative.html  Markdown narrative of MANIFESTO.md
     - foundations.html   rendered from FOUNDATIONS.md
     - workflow.html      rendered from WORKFLOW.md
     - faq.html           rendered from FAQ.md
     - agents.html        rendered from AGENTS.md
     - contributing.html  rendered from CONTRIBUTING.md
     - readme.html        rendered from README.md (English)
     - readme-ru.html     rendered from README.ru.md (Russian)
     - packets.html       list of all packets with mermaid graph
     - extensions.html    the three extensions only
     - packets/NAME.html  one HTML page per packet
     - assets/style.css   project stylesheet

   The dist directory is .gitignored. To deploy, copy dist to the
   gh-pages branch and push. *)

open Types

(* --- navigation links (English) --- *)

let nav_links = [
  ("home",       "Home",        "/");
  ("manifesto",  "Manifesto",   "/manifesto.html");
  ("readme",     "README",      "/readme.html");
  ("packets",    "Packets",     "/packets.html");
  ("foundations","Foundations", "/foundations.html");
  ("extensions", "Extensions",  "/extensions.html");
  ("workflow",   "Workflow",    "/workflow.html");
  ("faq",        "FAQ",         "/faq.html");
  ("agents",     "Agents",      "/agents.html");
]

let render_nav active =
  let items = String.concat "" (List.map
    (fun (key, label, href) ->
      let cls = if key = active then {| class="nav-link active"|} else {| class="nav-link"|} in
      Printf.sprintf {|<a%s href="%s">%s</a>|} cls href label)
    nav_links) in
  Printf.sprintf
    {|<nav class="site-nav"><div class="nav-inner"><a class="brand" href="/">math-coding</a>%s</div></nav>|}
    items

let render_footer =
  {|<footer class="site-footer">
<a href="/">math-coding v2.0-Y</a> &middot; Living Beings License &middot;
Generated by <code>mathc render</code>
</footer>|}

let render_page ~nav_key ~title ~body =
  Printf.sprintf
    {|<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>%s &mdash; math-coding</title>
<link rel="stylesheet" href="/assets/style.css">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad: true});</script>
</head>
<body>
%s
<main>
%s
</main>
%s
</body>
</html>|}
    title
    (render_nav nav_key)
    body
    render_footer

let html_escape s =
  let b = Buffer.create (String.length s) in
  String.iter (fun c ->
    match c with
    | '<' -> Buffer.add_string b "&lt;"
    | '>' -> Buffer.add_string b "&gt;"
    | '&' -> Buffer.add_string b "&amp;"
    | '"' -> Buffer.add_string b "&quot;"
    | '\'' -> Buffer.add_string b "&#39;"
    | _ -> Buffer.add_char b c)
  s;
  Buffer.contents b

(* --- Mermaid subgraph generation --- *)

let mermaid_wrapper content =
  Printf.sprintf
    {|<div class="mermaid">
%s
</div>|} content

let render_supersession_graph packets =
  let lines = ref ["graph LR"; "  %% supersession chains"] in
  List.iter
    (fun (older, newer) ->
      let older_clean = String.map (fun c -> if c = '/' || c = '-' then '_' else c) older in
      let newer_clean = String.map (fun c -> if c = '/' || c = '-' then '_' else c) newer in
      lines := Printf.sprintf "  %s --> %s" older_clean newer_clean :: !lines)
    packets;
  mermaid_wrapper (String.concat "\n" (List.rev !lines))

(* --- Packet HTML rendering --- *)

(* Compute path relative to math/. *)
let rel_path_of dir =
  let rec find_math (i : int) (path : string) : int option =
    if i + 5 > String.length path then None
    else if String.sub path i 5 = "math/" then Some i
    else find_math (i + 1) path
  in
  let dir_str : string = dir in
  match find_math 0 dir_str with
  | None -> Filename.basename dir
  | Some i ->
      let after = String.sub dir_str (i + 5) (String.length dir_str - i - 5) in
      let len = String.length after in
      if len > 0 && after.[len - 1] = '/' then
        String.sub after 0 (len - 1)
      else after

let badge_class = function
  | "applied" -> "badge-applied"
  | "draft"   -> "badge-draft"
  | "drift"   -> "badge-drift"
  | "stale"   -> "badge-stale"
  | _ -> "badge-stale"

let empty_value = "&mdash;"

let render_frontmatter d =
  let body_fields = [
    "schema_version", (match d.schema_version with "" -> empty_value | s -> s);
    "name", d.name;
    "proposition", d.proposition;
    "register", Types.register_to_string d.register;
    "state", Types.fsm_state_to_string d.state;
    "actor", Types.actor_to_string d.actor;
    "confidence", Printf.sprintf "%.2f" d.confidence;
    "superseded_by", (match d.superseded_by with None -> empty_value | Some s -> s);
    "beneficiary", Types.beneficiary_to_string d.beneficiary;
  ] in
  let body_str = String.concat "\n"
    (List.map (fun (k, v) ->
      Printf.sprintf {|"%s": "%s"|} k (html_escape v)) body_fields) in
  Printf.sprintf {|<pre class="frontmatter">
%s</pre>|} body_str

let render_packet_body body =
  let lines = String.split_on_char '\n' body in
  let b = Buffer.create 4096 in
  let in_code = ref false in
  let para = ref [] in
  let flush_para () =
    if !para <> [] then begin
      let joined = String.concat " " (List.rev !para) in
      Buffer.add_string b (Printf.sprintf "<p>%s</p>\n" (html_escape joined));
      para := []
    end
  in
  List.iter
    (fun raw ->
      let line = String.trim raw in
      if line = "```" then begin
        flush_para ();
        in_code := not !in_code;
        if !in_code then Buffer.add_string b "<pre><code>"
        else Buffer.add_string b "</code></pre>\n"
      end else if !in_code then
        Buffer.add_string b (Printf.sprintf "%s\n" (html_escape line))
      else if String.length line >= 3 && String.sub line 0 3 = "## " then begin
        flush_para ();
        Buffer.add_string b (Printf.sprintf "<h3>%s</h3>\n"
          (html_escape (String.sub line 3 (String.length line - 3))))
      end else if line = "" then
        flush_para ()
      else
        para := line :: !para)
    lines;
  flush_para ();
  Buffer.contents b

let render_packet_page packet_dir =
  match Parse.parse_packet ~rel_path:(rel_path_of packet_dir) packet_dir with
  | Error e -> render_page ~nav_key:"packets" ~title:"error"
      ~body:(Printf.sprintf "<p>Error: %s</p>" (html_escape e))
  | Ok d ->
    let packet_md = Filename.concat packet_dir "packet.md" in
    let ic = open_in packet_md in
    let raw =
      try really_input_string ic (in_channel_length ic) with _ -> ""
    in
    close_in ic;
    let body = Parse.extract_body raw in
    let lc = Lifecycle.compute d in
    let badge = badge_class (lifecycle_to_string lc) in
    let mermaid_chain =
      match d.superseded_by with
      | Some s when s <> "" ->
          mermaid_wrapper (Printf.sprintf "graph LR\n  %s --> %s"
            (String.map (fun c -> if c = '/' || c = '-' then '_' else c) d.name)
            (String.map (fun c -> if c = '/' || c = '-' then '_' else c) s))
      | _ -> "" in
    let body_html = render_packet_body body in
    let inner = Printf.sprintf
{|<a class="back-link" href="/packets.html">&larr; Packets</a>
<h1>%s <span class="badge %s">%s</span></h1>
<dl>%s</dl>
%s
<h2>Body</h2>
<div class="packet-body">%s</div>|}
      (html_escape d.name) badge (lifecycle_to_string lc)
      (render_frontmatter d)
      mermaid_chain
      body_html in
    render_page ~nav_key:"packets" ~title:d.name ~body:inner

(* --- Site generation --- *)

let write_file path content =
  let oc = open_out path in
  output_string oc content;
  close_out oc

let read_file path =
  let ic = open_in path in
  let content =
    try really_input_string ic (in_channel_length ic) with _ -> ""
  in
  close_in ic;
  content

let list_dir dir =
  try Array.to_list (Sys.readdir dir) with _ -> []

let rec list_packets acc dir =
  try
    let entries = Sys.readdir dir in
    Array.fold_left
      (fun acc entry ->
        let full = Filename.concat dir entry in
        let is_dir = try Sys.is_directory full with _ -> false in
        let has_packet = Sys.file_exists (Filename.concat full "packet.md") in
        if is_dir && has_packet then full :: acc
        else if is_dir then list_packets acc full
        else acc)
      acc entries
  with _ -> acc

(* Run pandoc and return true on success. *)
let run_pandoc ~input ~output ~extra ~workdir =
  let cmd = Printf.sprintf "cd %s && pandoc %s %s -o %s 2>&1"
    (Filename.quote workdir)
    (Filename.quote input) extra (Filename.quote output) in
  let rc = Sys.command cmd in
  rc = 0

(* Run pandoc on a file (in CWD) and return rendered fragment. *)
let render_pandoc_fragment ~input ~extra ~out_tmp =
  let cmd = Printf.sprintf "pandoc %s %s -o %s 2>&1"
    (Filename.quote input) extra (Filename.quote out_tmp) in
  let rc = Sys.command cmd in
  if rc <> 0 then begin
    Printf.printf "  pandoc failed for %s (rc=%d)\n" input rc;
    ""
  end else
    read_file out_tmp

let cmd_render () =
  let out_dir = "dist" in
  Printf.printf "mathc render: generating site under %s/\n" out_dir;
  let _ = Sys.command (Printf.sprintf "rm -rf %s && mkdir -p %s/assets %s/packets"
    out_dir out_dir out_dir) in

  (* Copy assets. *)
  if Sys.file_exists "assets/style.css" then begin
    let _ = Sys.command "cp assets/style.css dist/assets/" in
    Printf.printf "  + assets/style.css\n"
  end;

  (* Render the LaTeX model as the manifesto. *)
  let model_dir = "math/modeling" in
  if Sys.file_exists model_dir then begin
    let tex_files = List.filter (fun f -> Filename.check_suffix f ".tex")
      (list_dir model_dir) in
    (match tex_files with
     | [] -> ()
     | _ ->
        let tmp_dir = Filename.temp_file "mathcoding-manifest" ".d" in
        let _ = Sys.remove tmp_dir in
        let _ = Sys.command (Printf.sprintf "mkdir -p %s" (Filename.quote tmp_dir)) in
        List.iter (fun f ->
          let src = Filename.concat model_dir f in
          let dst = Filename.concat tmp_dir f in
          let _ = Sys.command (Printf.sprintf "cp %s %s"
            (Filename.quote src) (Filename.quote dst)) in
          ()) tex_files;
        let tmp_html = Filename.temp_file "manifesto-frag" ".html" in
        let ok = run_pandoc ~input:"math-coding.tex" ~output:tmp_html
          ~extra:"--mathjax" ~workdir:tmp_dir in
        if ok then begin
          let body = read_file tmp_html in
          let page = render_page ~nav_key:"manifesto"
            ~title:"math-coding: formal model" ~body in
          write_file "dist/manifesto.html" page;
          Printf.printf "  + manifesto.html (LaTeX rendered with MathJax)\n"
        end;
        Sys.remove tmp_html;
        let _ = Sys.command (Printf.sprintf "rm -rf %s" (Filename.quote tmp_dir)) in
        ())
  end;

  (* Render selected Markdown files via pandoc.
     Each FOO.md has an English version rendered to FOO.html.
     Optional FOO.ru.md is rendered to FOO.ru.html when present. *)
  let md_files = [
    ("README.md",       "readme.html");
    ("MANIFESTO.md",    "manifesto-narrative.html");
    ("FOUNDATIONS.md",  "foundations.html");
    ("WORKFLOW.md",     "workflow.html");
    ("FAQ.md",          "faq.html");
    ("AGENTS.md",       "agents.html");
    ("CONTRIBUTING.md", "contributing.html");
  ] in
  (* English versions. *)
  List.iter
    (fun (src, dst) ->
      if Sys.file_exists src then begin
        let title = Filename.basename (Filename.chop_suffix src ".md") in
        let tmp_html = Filename.temp_file "page-frag" ".html" in
        let body = render_pandoc_fragment ~input:src
          ~extra:"--mathjax" ~out_tmp:tmp_html in
        let page = render_page ~nav_key:(Filename.chop_suffix src ".md")
          ~title ~body in
        let out = Filename.concat out_dir dst in
        write_file out page;
        Sys.remove tmp_html;
        Printf.printf "  + %s\n" dst
      end)
    md_files;
  (* Russian .ru.md versions. *)
  List.iter
    (fun src ->
      let base = Filename.chop_suffix src ".md" in
      let ru_src = base ^ ".ru.md" in
      let dst = (Filename.basename base) ^ ".ru.html" in
      if Sys.file_exists ru_src then begin
        let title = Printf.sprintf "%s (Russian)" (Filename.basename base) in
        let tmp_html = Filename.temp_file "page-frag-ru" ".html" in
        let body = render_pandoc_fragment ~input:ru_src
          ~extra:"--mathjax" ~out_tmp:tmp_html in
        let page = render_page ~nav_key:base ~title ~body in
        let out = Filename.concat out_dir dst in
        write_file out page;
        Sys.remove tmp_html;
        Printf.printf "  + %s\n" dst
      end)
    (List.map fst md_files);

  (* Collect packets and chain info for the index/list pages. *)
  let packets = list_packets [] "math" in
  let packet_data = List.filter_map
    (fun dir ->
      match Parse.parse_packet ~rel_path:(rel_path_of dir) dir with
      | Ok d ->
        let lc = Lifecycle.compute d in
        Some (d.name, d.proposition, lc, d.superseded_by)
      | Error _ -> None)
    packets in

  (* Render each packet page. *)
  List.iter
    (fun (name, _, _, _) ->
      let dir = Filename.concat "math" name in
      let out = Filename.concat out_dir (Filename.concat "packets" (name ^ ".html")) in
      let html = render_packet_page dir in
      write_file out html;
      Printf.printf "  + packets/%s.html\n" name)
    packet_data;

  (* Compute supersession chains for the index page graph. *)
  let chains = List.filter_map
    (fun (n, _, _, sup) ->
      match sup with
      | Some s when s <> "" -> Some (n, s)
      | _ -> None)
    packet_data in

  (* Render packets.html (list of all packets with cards). *)
  let packet_cards = String.concat "\n"
    (List.map
      (fun (name, prop, lc, _) ->
        let lc_str = lifecycle_to_string lc in
        let cls = badge_class lc_str in
        Printf.sprintf {|<div class="packet-card">
<a href="/packets/%s.html">%s</a>
<div class="meta"><span class="badge %s">%s</span></div>
<p class="proposition">%s</p>
</div>|} name (html_escape name) cls lc_str (html_escape prop))
      packet_data) in
  let packets_body = Printf.sprintf
    {|<h1>Packets</h1>
<p class="meta">%d packets verified by the same kernel S</p>
<div class="packets-grid">
%s
</div>
<h2>Supersession chains</h2>
%s|}
    (List.length packet_data) packet_cards
    (render_supersession_graph chains) in
  let packets_page = render_page ~nav_key:"packets" ~title:"Packets"
    ~body:packets_body in
  write_file "dist/packets.html" packets_page;
  Printf.printf "  + packets.html\n";

  (* extensions.html: only process-fsm, dialectic-tas, actor-discipline. *)
  let ext_names = ["process-fsm"; "dialectic-tas"; "actor-discipline"] in
  let ext_data = List.filter (fun (n, _, _, _) -> List.mem n ext_names) packet_data in
  let ext_cards = String.concat "\n"
    (List.map
      (fun (name, prop, lc, _) ->
        let lc_str = lifecycle_to_string lc in
        Printf.sprintf {|<div class="packet-card">
<a href="/packets/%s.html">%s</a>
<div class="meta"><span class="badge %s">%s</span></div>
<p class="proposition">%s</p>
</div>|} name (html_escape name) (badge_class lc_str) lc_str
          (html_escape prop))
      ext_data) in
  let extensions_body = Printf.sprintf
    {|<h1>Extensions</h1>
<p>Three extensions add obligations to the packet schema and the
state machine: process-fsm governs FSM transitions,
dialectic-tas requires Thesis/Antithesis/Synthesis sections for
human judgments, and actor-discipline binds decisions to authors
through signed commits.</p>
<div class="packets-grid">
%s
</div>|}
    ext_cards in
  let extensions_page = render_page ~nav_key:"extensions"
    ~title:"Extensions" ~body:extensions_body in
  write_file "dist/extensions.html" extensions_page;
  Printf.printf "  + extensions.html\n";

  (* Render foundations.html: 5 foundation packets. *)
  let found_names = ["curry-howard"; "temporal"; "constructive"; "categorical"; "motivation"] in
  let found_data = List.filter (fun (n, _, _, _) -> List.mem n found_names) packet_data in
  let found_cards = String.concat "\n"
    (List.map
      (fun (name, prop, lc, _) ->
        let lc_str = lifecycle_to_string lc in
        Printf.sprintf {|<div class="packet-card">
<a href="/packets/%s.html">%s</a>
<div class="meta"><span class="badge %s">%s</span></div>
<p class="proposition">%s</p>
</div>|} name (html_escape name) (badge_class lc_str) lc_str
          (html_escape prop))
      found_data) in
  let foundations_body = Printf.sprintf
    {|<h1>Foundations</h1>
<p>Five foundational propositions ground the convention. Each is
itself a packet, verified by the same kernel S.</p>
<div class="packets-grid">
%s
</div>|}
    found_cards in
  let foundations_page = render_page ~nav_key:"foundations"
    ~title:"Foundations" ~body:foundations_body in
  write_file "dist/foundations.html" foundations_page;
  Printf.printf "  + foundations.html\n";

  (* Render index.html -- front page. *)
  let cards_overview = String.concat "\n"
    (List.map
      (fun (name, prop, _, _) ->
        Printf.sprintf {|<div class="packet-card">
<a href="/packets/%s.html">%s</a>
<p class="proposition">%s</p>
</div>|} name (html_escape name) (html_escape prop))
      packet_data) in
  let stats = Printf.sprintf "%d packets &middot; 1 binary &middot; 1 convention"
    (List.length packet_data) in
  let index_body = Printf.sprintf
    {|<section class="hero">
<h1>math-coding</h1>
<p class="tagline">A practice of recording decisions before code.</p>
<p class="meta">%s &middot; v2.0-Y &middot; Y-fixed point</p>
</section>

<h2>What it is</h2>
<p>math-coding is a convention in which every non-trivial
architectural decision exists as a <em>packet</em>: an explicit
proposition bound to code through a git SHA and verified by a
single kernel. Decisions evolve through <em>supersession</em>,
not through editing.</p>

<h2>Supersession chains</h2>
<p>Each packet has <code>superseded_by</code>. The relation is
a strict partial order; chains form a directed acyclic graph:</p>
%s

<h2>Packets (%d)</h2>
<div class="packets-grid">
%s
</div>

<h2>Eight principles</h2>
<ol>
<li><strong>Decision is a triple</strong> &mdash; (proposition, code, witness); Curry-Howard.</li>
<li><strong>Lifecycle is computed</strong> &mdash; L(decision, repo) from git, not stored.</li>
<li><strong>Proof is reproducible</strong> &mdash; re-run + exit code.</li>
<li><strong>Supersession is SPO</strong> &mdash; irreflexive, asymmetric, transitive.</li>
<li><strong>Register and why</strong> &mdash; A1 Care restored.</li>
<li><strong>FSM with one forbidden</strong> &mdash; draft &rarr; reviewed forbidden.</li>
<li><strong>Thesis / Antithesis / Synthesis</strong> &mdash; dialectic for judgments.</li>
<li><strong>Signed commits fix author</strong> &mdash; three signing modes.</li>
</ol>

<h2>Quick start</h2>
<pre><code>mathc init
mathc record my-decision "TTL = 60s with manual invalidation"
git add math/my-decision/ &amp;&amp; git commit -m "my-decision: ttl policy"
mathc amend my-decision
git add math/my-decision/witness &amp;&amp; git commit -m "my-decision: witness"
mathc check</code></pre>

<p>Install: <code>nix develop --command sh scripts/install.sh</code>.
Binary lands at <code>$XDG_DATA_HOME/math-coding/current/mathc</code>.</p>

<h2>Project layout</h2>
<ul>
<li><code>README.md</code> &mdash; English teaser (this site's <a href="/readme.html">readme.html</a>)</li>
<li><code>README.ru.md</code> &mdash; Russian parallel (<a href="/readme-ru.html">readme-ru.html</a>)</li>
<li><code>MANIFESTO.md</code> &mdash; eight principles (<a href="/manifesto-narrative.html">narrative</a>, <a href="/manifesto.html">formal model</a>)</li>
<li><code>FOUNDATIONS.md</code> &mdash; packet descriptions (<a href="/foundations.html">foundations.html</a>)</li>
<li><code>WORKFLOW.md</code> &mdash; daily + brownfield (<a href="/workflow.html">workflow.html</a>)</li>
<li><code>FAQ.md</code> &mdash; ten frequent questions (<a href="/faq.html">faq.html</a>)</li>
<li><code>AGENTS.md</code> &mdash; protocol for AI agents (<a href="/agents.html">agents.html</a>)</li>
<li><code>CONTRIBUTING.md</code> &mdash; KNOWN DIVERGENCE convention (<a href="/contributing.html">contributing.html</a>)</li>
<li><code>math/modeling/*.tex</code> &mdash; formal LaTeX model</li>
<li><code>math/&lt;name&gt;/packet.md</code> &mdash; convention packets</li>
</ul>|}
    stats (render_supersession_graph chains)
    (List.length packet_data) cards_overview in
  let index_page = render_page ~nav_key:"home" ~title:"math-coding v2.0-Y"
    ~body:index_body in
  write_file "dist/index.html" index_page;
  Printf.printf "  + index.html\n";

  Printf.printf "mathc render: dist/ generated (%d pages)\n"
    (List.length packet_data + 13)