#!/bin/sh
# core/install/install.sh — math-coding v0.993 shared installer.
#
# Usage:
#   sh core/install/install.sh <target-dir> [--local] [--gitignore]
#
# Default (shared) install:
#   1. Copy payload once to $XDG_DATA_HOME/math-coding/<ver>/.
#   2. Update or create a `current` symlink.
#   3. Write a 25-line wrapper + .mathrc + math/README.md into <target-dir>.
#
# --local:
#   Reproduce the legacy layout: copy payload into <target-dir>/.math-coding/.
#   Use this for hermetic CI runs and sandboxed agents without $HOME.
#
# --gitignore:
#   Add `.math-coding/` to .gitignore (only meaningful with --local).

set -u

. "$(dirname "$0")/../lib/common.sh"

usage() {
    cat <<EOF >&2
usage: install.sh <target-dir> [--local] [--gitignore]

Default install puts the payload at
  \${XDG_DATA_HOME:-\$HOME/.local/share}/math-coding/<ver>/
and writes a 25-line wrapper + .mathrc + math/README.md into <target-dir>.

Options:
    --local        legacy layout: payload into <target>/.math-coding/
    --gitignore    (with --local) add .math-coding/ to .gitignore
    -h | --help    this message
EOF
    exit 2
}

TARGET=""
LAYOUT="shared"
GITIGNORE_OPT=""

while [ $# -gt 0 ]; do
    case "$1" in
        --local) LAYOUT="local"; shift ;;
        --gitignore) GITIGNORE_OPT="1"; shift ;;
        --help|-h) usage ;;
        -*) echo "unknown flag: $1" >&2; usage ;;
        *) TARGET="$1"; shift ;;
    esac
done

[ -z "$TARGET" ] && usage
TARGET="$(cd "$TARGET" && pwd)"
[ -d "$TARGET" ] || { echo "error: $TARGET is not a directory" >&2; exit 2; }

# Resolve version from source-repo VERSION file, fallback to package.
VERSION="${MATH_CODING_VERSION:-}"
if [ -z "$VERSION" ] && [ -f "$REPO_ROOT/VERSION" ]; then
    VERSION=$(cat "$REPO_ROOT/VERSION")
fi
[ -z "$VERSION" ] && VERSION="0.993-dev"

# 1. Payload: source dirs to ship.
PAYLOAD_DIRS="core extensions"

# 2. Wrapper template (project-local).
WRAPPER_TEMPLATE='#!/bin/sh
# math-coding wrapper — resolves to shared install or local .math-coding/.
# Generated by math-coding install; safe to commit.
set -u

resolve_target() {
    if [ -n "${MATH_CODING_HOME:-}" ] && [ -x "${MATH_CODING_HOME}/current/math-coding" ]; then
        printf "%s" "${MATH_CODING_HOME}/current"
        return 0
    fi
    for d in "${XDG_DATA_HOME:-$HOME/.local/share}/math-coding/current" \
             "/usr/local/share/math-coding/current" \
             "/opt/math-coding/current"; do
        if [ -x "$d/math-coding" ]; then
            printf "%s" "$d"
            return 0
        fi
    done
    if [ -x "./.math-coding/math-coding" ]; then
        printf "%s" "./.math-coding"
        return 0
    fi
    return 1
}

if target=$(resolve_target); then
    exec sh "$target/math-coding" "$@"
else
    echo "math-coding: no install found. Run:" >&2
    echo "    sh /path/to/math-coding-shared/core/install/install.sh <project>" >&2
    exit 127
fi
'

if [ "$LAYOUT" = "shared" ]; then
    DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
    DATA_DIR="$DATA/math-coding"
    VERSION_DIR="$DATA_DIR/$VERSION"
    CURRENT_LINK="$DATA_DIR/current"

    mkdir -p "$VERSION_DIR" || { echo "error: cannot create $VERSION_DIR" >&2; exit 1; }

    for d in $PAYLOAD_DIRS; do
        if [ -d "$REPO_ROOT/$d" ]; then
            rm -rf "$VERSION_DIR/$d"
            cp -R "$REPO_ROOT/$d" "$VERSION_DIR/$d"
        fi
    done

    # Ship the dispatcher alongside the payload.
    if [ -f "$REPO_ROOT/math-coding" ]; then
        cp "$REPO_ROOT/math-coding" "$VERSION_DIR/math-coding"
        chmod +x "$VERSION_DIR/math-coding"
    fi

    # Symlink current → <ver> (replace if present and not same target).
    if [ -L "$CURRENT_LINK" ] || [ -e "$CURRENT_LINK" ]; then
        cur_target=$(readlink "$CURRENT_LINK" 2>/dev/null || true)
        if [ "$cur_target" != "$VERSION" ]; then
            rm -f "$CURRENT_LINK"
            ln -s "$VERSION" "$CURRENT_LINK"
        fi
    else
        ln -s "$VERSION" "$CURRENT_LINK"
    fi

    # Write wrapper + .mathrc + math/README.md into project.
    WRAPPER_PATH="$TARGET/math-coding"
    printf '%s\n' "$WRAPPER_TEMPLATE" > "$WRAPPER_PATH"
    chmod +x "$WRAPPER_PATH"

    if [ ! -f "$TARGET/.mathrc" ]; then
        cat > "$TARGET/.mathrc" <<'EOF'
# math-coding configuration
mode: standard
role: developer
math_dir: math
lookahead_ok: 0
committed: 0

required_approvals: 1
self_approve_allowed: yes
placeholder_detection: standard
abandoned_threshold_days: 90
self_critique_echo: yes
lifecycle_abandoned_enabled: yes
evidence_strict: no
EOF
    fi

    if [ ! -d "$TARGET/math" ]; then
        mkdir -p "$TARGET/math"
        cat > "$TARGET/math/README.md" <<'EOF'
# math/

This directory holds the project's packets. Each packet has
three mandatory files: `packet.yaml`, `decision.md`,
`refinement.md`. Two optional files (`task.md`,
`assumptions.yaml`) are auto-generated.

## Workflow

### 1. Create a packet

Write a spec with seven fields:

    cat > /tmp/spec.yaml <<YAML
    proposition: |
      <one sentence — the claim>
    outcome: |
      <one sentence — what becomes true>
    YAML

    sh ./math-coding create my-feature --from /tmp/spec.yaml

### 2. Implement and commit

    git add .
    git commit -m "my-feature: implementation"

### 3. Apply (record SHA witness)

    sh ./math-coding apply my-feature

### 4. Review (peer approval — required for applied)

    sh ./math-coding review my-feature --approve --note="tests pass"

### 5. Lifecycle transitions

    sh ./math-coding lifecycle my-feature retired --reason=deprecation
    sh ./math-coding lifecycle my-feature abandoned
    sh ./math-coding lifecycle my-feature applied    # re-apply

### 6. Supersession

    sh ./math-coding lifecycle old-name retired --reason=supersession
    sh ./math-coding create new-name --from spec.yaml
    # then add `supersession: math/old-name/` to new-name/packet.yaml

EOF
    fi

    echo "installed math-coding (shared) → $VERSION_DIR"
    echo "  wrapper:  $WRAPPER_PATH"
    echo "  symlink:  $CURRENT_LINK → $VERSION"
    echo "  .mathrc:  $TARGET/.mathrc"
    echo "  math/:    $TARGET/math/"
    echo ""
    echo "verify: sh $WRAPPER_PATH probe"
else
    # --local: legacy in-repo copy.
    DEST="$TARGET/.math-coding"
    if [ -d "$DEST" ]; then
        echo "error: $DEST already exists" >&2
        exit 1
    fi
    mkdir -p "$DEST"

    for d in $PAYLOAD_DIRS; do
        if [ -d "$REPO_ROOT/$d" ]; then
            cp -R "$REPO_ROOT/$d" "$DEST/$d"
        fi
    done
    if [ -f "$REPO_ROOT/math-coding" ]; then
        cp "$REPO_ROOT/math-coding" "$DEST/math-coding"
        chmod +x "$DEST/math-coding"
    fi

    if [ ! -f "$TARGET/.mathrc" ]; then
        cat > "$TARGET/.mathrc" <<'EOF'
mode: standard
role: developer
math_dir: math
lookahead_ok: 0
committed: 0
required_approvals: 1
self_approve_allowed: yes
placeholder_detection: standard
abandoned_threshold_days: 90
self_critique_echo: yes
lifecycle_abandoned_enabled: yes
evidence_strict: no
EOF
    fi

    if [ "$GITIGNORE_OPT" = "1" ]; then
        GITIGNORE="$TARGET/.gitignore"
        if [ -f "$GITIGNORE" ]; then
            grep -v "^.math-coding/$" "$GITIGNORE" > "$GITIGNORE.tmp" 2>/dev/null
            if ! grep -q "^.math-coding/$" "$GITIGNORE"; then
                echo ".math-coding/" >> "$GITIGNORE"
            fi
            rm -f "$GITIGNORE.tmp"
        else
            echo ".math-coding/" > "$GITIGNORE"
        fi
    fi

    if [ ! -d "$TARGET/math" ]; then
        mkdir -p "$TARGET/math"
        printf '# math/\n\nSee .math-coding/math-coding help.\n' > "$TARGET/math/README.md"
    fi

    echo "installed math-coding (local) → $DEST"
    echo "  dispatcher: $DEST/math-coding"
    echo ""
    echo "verify: sh $DEST/math-coding probe"
fi
