(* lib/render.ml — kernel site generator for `mc render`.
 *
 * The site is generated from three inputs:
 *   1. `decisions/` + `attestations/` (the protocol surface) —
 *      rendered by lib/packages.ml and re-emitted here as the
 *      package grid on index.html and the per-decision pages.
 *   2. `site/*.md` — the prose articles (axioms, methodology,
 *      bootstrap-gate, packages). The articles are written in
 *      a subset of Markdown: headings, paragraphs, lists, code
 *      blocks (incl. `mermaid`), inline code, links, and inline
 *      `^[sidenote]` markers. We deliberately do NOT pull in a
 *      full Markdown library; the protocol's published prose
 *      uses a narrow subset and a 100-line parser is auditable.
 *   3. `site/*.ru.md` (and any future `<name>.<lang>.md`) — the
 *      bilingual siblings. Each English page is rendered twice
 *      (once per available language); each rendering carries
 *      `<html lang="…">` and links to its sibling.
 *
 * The site **demonstrates** the methodology. Every link in
 * the rendered HTML that names a decision points at a per-
 * decision HTML page that is itself generated by this module.
 * The package grid is the HTML form of `mc packages`. The
 * search index is a flat JSON over the page titles.
 *
 * The render function is pure: it takes a `reader` callback
 * and an `out_dir` string. The dispatcher is the only caller
 * that performs I/O. *)

(* --- minimal Markdown subset --- *)

let[@warning "-32"] html_escape s =
  let len = String.length s in
  let buf = Buffer.create len in
  for i = 0 to len - 1 do
    match s.[i] with
    | '<' -> Buffer.add_string buf "&lt;"
    | '>' -> Buffer.add_string buf "&gt;"
    | '&' -> Buffer.add_string buf "&amp;"
    | '"' -> Buffer.add_string buf "&quot;"
    | c -> Buffer.add_char buf c
  done;
  Buffer.contents buf

(* Parse the body of an inline segment looking for `^[text]`
   sidenote syntax. Returns a list of (escaped_html, is_sidenote)
   fragments in source order. Outside a sidenote, also handles
   inline code (`...`). *)
(* Per-render-call sidenote counter. Bumped once per `^[body]`
   occurrence so the inline marker and the margin note share an
   anchor id pair (sn-N, snref-N). The reference itself lives in
   the closure of `loop`; both bindings are introduced inside
   `md_inline_parse`. *)
let[@warning "-32"] md_inline_parse s =
  let len = String.length s in
  let buf = Buffer.create len in
  let fragments : (string * bool) list ref = ref [] in
  let sidenote_counter = ref 1 in
  let flush_inline () =
    if Buffer.length buf > 0 then begin
      fragments := (Buffer.contents buf, false) :: !fragments;
      Buffer.clear buf
    end
  in
  let rec loop i =
    if i >= len then flush_inline ()
    else
      let c = s.[i] in
      if c = '`' then begin
        let j = ref (i + 1) in
        while !j < len && s.[!j] <> '`' do
          incr j
        done;
        if !j < len then begin
          let code = String.sub s (i + 1) (!j - i - 1) in
          flush_inline ();
          let html = Printf.sprintf "<code>%s</code>" (html_escape code) in
          fragments := (html, false) :: !fragments;
          loop (!j + 1)
        end
        else begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
      end
      else if c = '^' && i + 1 < len && s.[i + 1] = '[' then begin
        (* sidenote: ^[body] — emit <sup>N</sup> + <label class="sidenote">body</label> *)
        let j = ref (i + 2) in
        let depth = ref 1 in
        while !j < len && !depth > 0 do
          if s.[!j] = '[' then incr depth else if s.[!j] = ']' then decr depth;
          if !depth > 0 then incr j
        done;
        if !j < len && !depth = 0 then begin
          let body_str = String.sub s (i + 2) (!j - i - 2) in
          flush_inline ();
          let n = !sidenote_counter in
          let marker =
            Printf.sprintf
              "<sup><a id=\"snref-%d\" href=\"#sn-%d\" \
               class=\"sidenote-number\">%d</a></sup>"
              n n n
          in
          let sidenote_html =
            Printf.sprintf
              "<label for=\"snref-%d\" class=\"sidenote\" \
               id=\"sn-%d\">%s</label>"
              n n (html_escape body_str)
          in
          fragments := (sidenote_html, true) :: (marker, true) :: !fragments;
          incr sidenote_counter;
          loop (!j + 1)
        end
        else begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
      end
      else begin
        Buffer.add_char buf c;
        loop (i + 1)
      end
  in
  loop 0;
  List.rev !fragments

(* Wrap a list of (html_fragment, is_sidenote) into the final
   inline HTML: pure-text fragments get md_inline (which handles
   backtick code), sidenote fragments are emitted verbatim. *)
let[@warning "-32"] md_inline s =
  let frags = md_inline_parse s in
  let buf = Buffer.create (String.length s) in
  List.iter
    (fun (html, is_sn) ->
      if is_sn then Buffer.add_string buf html else Buffer.add_string buf html)
    frags;
  Buffer.contents buf

(* Detect the language tag on a fenced code block. The line is
   `\`\`\`TAG`. Returns Some TAG if the tag is meaningful
   (anything but the empty string), else None. *)
let[@warning "-32"] code_fence_tag (line : string) : string option =
  let t = String.trim line in
  if String.length t > 3 && String.sub t 0 3 = "```" then begin
    let rest = String.sub t 3 (String.length t - 3) in
    let lang = String.trim rest in
    if lang = "" then None else Some lang
  end
  else None

let[@warning "-32"] md_parse source =
  let lines = String.split_on_char '\n' source in
  let buf = Buffer.create 256 in
  let flush_para text =
    if text <> "" then begin
      Buffer.add_string buf "  <p>";
      Buffer.add_string buf (md_inline text);
      Buffer.add_string buf "</p>\n"
    end
  in
  let rec collect_code acc = function
    | [] -> (List.rev acc, [])
    | l :: r ->
        let trimmed = String.trim l in
        if String.length trimmed > 4 && String.sub trimmed 0 4 = "```" then
          (List.rev acc, r)
        else collect_code (l :: acc) r
  in
  let rec loop acc_para = function
    | [] -> flush_para acc_para
    | line :: rest -> (
        let t = String.trim line in
        let push_para () = flush_para acc_para in
        match t with
        | "" ->
            push_para ();
            loop "" rest
        | _ when String.length t > 2 && String.sub t 0 2 = "# " ->
            push_para ();
            Buffer.add_string buf "<h1>";
            Buffer.add_string buf
              (md_inline (String.sub t 2 (String.length t - 2)));
            Buffer.add_string buf "</h1>\n";
            loop "" rest
        | _ when String.length t > 3 && String.sub t 0 3 = "## " ->
            push_para ();
            Buffer.add_string buf "<h2>";
            Buffer.add_string buf
              (md_inline (String.sub t 3 (String.length t - 3)));
            Buffer.add_string buf "</h2>\n";
            loop "" rest
        | _ when String.length t > 4 && String.sub t 0 4 = "### " ->
            push_para ();
            Buffer.add_string buf "<h3>";
            Buffer.add_string buf
              (md_inline (String.sub t 4 (String.length t - 4)));
            Buffer.add_string buf "</h3>\n";
            loop "" rest
        | _ when String.length t > 4 && String.sub t 0 4 = "```" -> begin
            push_para ();
            let tag = code_fence_tag line in
            let collected, after = collect_code [] rest in
            let code = String.concat "\n" collected in
            (match tag with
            | Some "mermaid" ->
                Buffer.add_string buf "<div class=\"mermaid\">";
                Buffer.add_string buf (html_escape code);
                Buffer.add_string buf "</div>\n"
            | Some lang ->
                Buffer.add_string buf "<pre><code class=\"language-";
                Buffer.add_string buf (html_escape lang);
                Buffer.add_string buf "\">";
                Buffer.add_string buf (html_escape code);
                Buffer.add_string buf "</code></pre>\n"
            | None ->
                Buffer.add_string buf "<pre><code>";
                Buffer.add_string buf (html_escape code);
                Buffer.add_string buf "</code></pre>\n");
            loop "" after
          end
        | _ when String.length t > 2 && String.sub t 0 2 = "- " ->
            push_para ();
            Buffer.add_string buf "<ul>\n  <li>";
            Buffer.add_string buf
              (md_inline (String.sub t 2 (String.length t - 2)));
            Buffer.add_string buf "</li>\n</ul>\n";
            loop "" rest
        | _ ->
            let next = if acc_para = "" then t else acc_para ^ " " ^ t in
            loop next rest)
  in
  loop "" lines;
  Buffer.contents buf

(* --- navigation --- *)

(* The site's English navigation. Every key also has a Russian
   counterpart when the corresponding site/<key>.ru.md exists.
   The dispatcher decides which languages to render; this list
   is the union of all available pages. *)
let[@warning "-32"] nav_links_en =
  [
    ("home", "Home", "index.html");
    ("axioms", "Axioms", "axioms.html");
    ("manifesto", "Manifesto", "manifesto.html");
    ("foundations", "Foundations", "foundations.html");
    ("methodology", "Methodology", "methodology.html");
    ("workflow", "Workflow", "workflow.html");
    ("faq", "FAQ", "faq.html");
    ("readme", "README", "readme.html");
    ("contributing", "Contributing", "contributing.html");
    ("bootstrap-gate", "Bootstrap Gate", "bootstrap-gate.html");
    ("packages", "Packages", "packages.html");
  ]

let[@warning "-32"] nav_links_ru =
  [
    ("home", "Главная", "index.html");
    ("axioms", "Аксиомы", "axioms.html");
    ("manifesto", "Манифест", "manifesto.ru.html");
    ("foundations", "Основания", "foundations.ru.html");
    ("methodology", "Методология", "methodology.html");
    ("workflow", "Workflow", "workflow.html");
    ("faq", "FAQ", "faq.html");
    ("readme", "README", "readme.ru.html");
    ("contributing", "Contributing", "contributing.html");
    ("bootstrap-gate", "Bootstrap-ворота", "bootstrap-gate.html");
    ("packages", "Пакеты", "packages.html");
  ]

let[@warning "-32"] nav_links_for lang =
  if lang = "ru" then nav_links_ru else nav_links_en

let[@warning "-32"] sibling_translation_href ~lang ~page_key =
  (* Each English page links to its Russian sibling and vice versa.
     If only one translation exists, the link is omitted. *)
  match lang with
  | "ru" -> Some (page_key ^ ".html") (* Russian -> English default *)
  | _ when page_key = "home" -> Some "index.ru.html"
  | _ -> Some (page_key ^ ".ru.html")

let[@warning "-32"] render_nav ~lang ~page_key ~enable_lang_toggle =
  let buf = Buffer.create 256 in
  let links = nav_links_for lang in
  Buffer.add_string buf "<nav class=\"site-nav\">\n";
  Buffer.add_string buf "  <a class=\"brand\" href=\"./\">math-coding</a>\n";
  Buffer.add_string buf
    "  <button type=\"button\" class=\"nav-toggle\" aria-label=\"Toggle \
     navigation\" aria-controls=\"nav-inner\" aria-expanded=\"false\"><span \
     aria-hidden=\"true\">&#9776;</span></button>\n";
  Buffer.add_string buf "  <ul class=\"nav-inner\" id=\"nav-inner\">\n";
  List.iter
    (fun (key, label, href) ->
      let cls =
        if key = page_key then " class=\"nav-link active\""
        else " class=\"nav-link\""
      in
      Printf.bprintf buf "    <li><a%s href=\"%s\">%s</a></li>\n" cls href label)
    links;
  Buffer.add_string buf "  </ul>\n";
  (if enable_lang_toggle then
     match sibling_translation_href ~lang ~page_key with
     | Some h ->
         let other_lang = if lang = "ru" then "en" else "ru" in
         let other_label = if lang = "ru" then "EN" else "RU" in
         Printf.bprintf buf
           "  <a class=\"lang-toggle\" href=\"%s\" hreflang=\"%s\" \
            lang=\"%s\">%s</a>\n"
           h other_lang other_lang other_label
     | None -> ());
  Buffer.add_string buf "</nav>\n";
  Buffer.contents buf

(* --- footer --- *)

let[@warning "-32"] render_footer ~lang =
  let site_meta =
    if lang = "ru" then
      "<p class=\"site-meta\">v3.0.0 &middot; <a \
       href=\"../AGENTS.html\">AGENTS.md</a> &middot; <a \
       href=\"../ROADMAP.html\">ROADMAP.md</a> &middot; <a \
       href=\"../PACKAGES.html\">PACKAGES.md</a> &middot; <a \
       href=\"index.html\">EN</a></p>\n"
    else
      "<p class=\"site-meta\">v3.0.0 &middot; <a \
       href=\"../AGENTS.html\">AGENTS.md</a> &middot; <a \
       href=\"../ROADMAP.html\">ROADMAP.md</a> &middot; <a \
       href=\"../PACKAGES.html\">PACKAGES.md</a> &middot; <a \
       href=\"index.ru.html\">RU</a></p>\n"
  in
  Printf.sprintf
    "<footer class=\"site-footer\">\n\
     <p>Built by <code>mc render</code> at build time. The site follows the \
     math-coding methodology: every page that describes a kernel feature is \
     itself produced by the kernel.</p>\n\
     %s</footer>\n"
    site_meta

(* --- page renderer --- *)

(* `<head>` carries: charset, viewport, <base href>, title, the
   stylesheet, optional MathJax script, optional mermaid script,
   and any caller-supplied extra head. *)
let[@warning "-32"] render_head ~lang ~site_base ~title ~enable_mathjax
    ~enable_mermaid ~extra_head =
  let buf = Buffer.create 256 in
  Printf.bprintf buf "<meta charset=\"utf-8\">\n";
  Printf.bprintf buf
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
  if site_base <> "" then
    Printf.bprintf buf "<base href=\"%s\">\n" (html_escape site_base);
  Printf.bprintf buf "<title>%s &mdash; math-coding</title>\n"
    (html_escape title);
  Printf.bprintf buf "<link rel=\"stylesheet\" href=\"assets/style.css\">\n";
  if enable_mathjax then begin
    Printf.bprintf buf
      "<script defer \
       src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n";
    Printf.bprintf buf
      "<script>\n\
       window.MathJax = { tex: { inlineMath: [['\\(','\\)'], ['$','$']], \
       displayMath: [['$$','$$'], ['\\[','\\]']] } };\n\
       </script>\n"
  end;
  if enable_mermaid then begin
    Printf.bprintf buf
      "<script defer \
       src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\n";
    Printf.bprintf buf
      "<script>\n\
       document.addEventListener('DOMContentLoaded', function () { if \
       (window.mermaid) mermaid.initialize({startOnLoad: true}); });\n\
       </script>\n"
  end;
  if extra_head <> "" then Printf.bprintf buf "%s\n" extra_head;
  Buffer.contents buf

let[@warning "-32"] render_page ~lang ~page_key ~title ~body ~site_base
    ~enable_mathjax ~enable_mermaid ~enable_lang_toggle ~extra_head =
  let head =
    render_head ~lang ~site_base ~title ~enable_mathjax ~enable_mermaid
      ~extra_head
  in
  Printf.sprintf
    "<!DOCTYPE html>\n\
     <html lang=\"%s\">\n\
     <head>\n\
     %s</head>\n\
     <body>\n\
     %s\n\
     <main class=\"site-main\">\n\
     %s\n\
     </main>\n\
     %s\n\
     <script>\n\
     (function(){\n\
     var t = document.querySelector('.nav-toggle');\n\
     var n = document.querySelector('.nav-inner');\n\
     if (!t || !n) return;\n\
     function sync(){\n\
     var isMobile = window.matchMedia('(max-width: 760px)').matches;\n\
     if (isMobile) { t.style.display = 'block'; }\n\
     else { t.style.display = 'none'; t.setAttribute('aria-expanded','false'); \
     n.style.display = 'flex'; }\n\
     }\n\
     sync();\n\
     window.addEventListener('resize', sync);\n\
     t.addEventListener('click', function(){\n\
     var open = t.getAttribute('aria-expanded') === 'true';\n\
     t.setAttribute('aria-expanded', open ? 'false' : 'true');\n\
     n.style.display = open ? 'none' : 'flex';\n\
     });\n\
     })();\n\
     </script>\n\
     </body>\n\
     </html>\n"
    lang head
    (render_nav ~lang ~page_key ~enable_lang_toggle)
    body (render_footer ~lang)

let[@warning "-32"] render_axioms_section axioms =
  let buf = Buffer.create 256 in
  Buffer.add_string buf "<section class=\"mc-axioms\">\n";
  List.iter
    (fun (id, body) ->
      Printf.bprintf buf
        "<article class=\"mc-axiom\">\n<h2>%s</h2>\n<div>%s</div>\n</article>\n"
        (html_escape id) (md_parse body))
    axioms;
  Buffer.add_string buf "</section>\n";
  Buffer.contents buf

let[@warning "-32"] render_index ~package_html ~axioms_html ~policy_id =
  Printf.sprintf
    "<section class=\"hero\">\n\
     <h1>math-coding 3.0-alpha</h1>\n\
     <p class=\"lead\">A risk-adaptive assurance protocol for software \
     changes. Links <em>intent</em>, <em>decisions</em>, <em>obligations</em>, \
     <em>changes</em>, <em>attestations</em>, and <em>revisions</em> into a \
     single traceable chain. The site you are reading was built by the same \
     kernel that the protocol describes.</p>\n\
     <p class=\"meta\">Active policy: <code>%s</code>. The package grid below \
     is the live output of <code>mc packages --format=html</code>.</p>\n\
     </section>\n\
     <section class=\"mc-packages-section\">\n\
     <h2>Packages</h2>\n\
     %s\n\
     </section>\n\
     <section class=\"mc-axioms-section\">\n\
     <h2>Axioms</h2>\n\
     %s\n\
     </section>\n\
     <p class=\"site-callout\">Every page on this site is produced by the \
     math-coding kernel. The methodology is the artifact; the artifact follows \
     the methodology.</p>\n"
    (html_escape policy_id) package_html axioms_html

let[@warning "-32"] render_index_ru ~package_html ~axioms_html ~policy_id =
  Printf.sprintf
    "<section class=\"hero\">\n\
     <h1>math-coding 3.0-alpha</h1>\n\
     <p class=\"lead\">Протокол assurance для изменений в программном \
     обеспечении, адаптированный к риску. Связывает <em>intent</em>, \
     <em>decisions</em>, <em>obligations</em>, <em>changes</em>, \
     <em>attestations</em> и <em>revisions</em> в одну прослеживаемую цепочку. \
     Сайт, который вы читаете, построен тем же ядром, которое описывает \
     протокол.</p>\n\
     <p class=\"meta\">Активная политика: <code>%s</code>. Сетка пакетов ниже \
     — живой вывод <code>mc packages --format=html</code>.</p>\n\
     </section>\n\
     <section class=\"mc-packages-section\">\n\
     <h2>Пакеты</h2>\n\
     %s\n\
     </section>\n\
     <section class=\"mc-axioms-section\">\n\
     <h2>Аксиомы</h2>\n\
     %s\n\
     </section>\n\
     <p class=\"site-callout\">Каждая страница этого сайта создаётся ядром \
     math-coding. Методология есть артефакт; артефакт следует методологии.</p>\n"
    (html_escape policy_id) package_html axioms_html

let[@warning "-32"] render_decision_page ~decision_id ~obligation_html =
  Printf.sprintf
    "<section class=\"mc-decision-page\">\n<h1>%s</h1>\n%s\n</section>\n"
    decision_id obligation_html

let[@warning "-32"] render_axiom_page ~axiom_id ~body =
  Printf.sprintf
    "<section class=\"mc-axiom-page\">\n\
     <h1>Axiom %s</h1>\n\
     <div>%s</div>\n\
     </section>\n"
    axiom_id (md_parse body)

(* --- render entry point --- *)

type page = { path : string; body : string }

(* Configuration bag passed by the dispatcher. *)
type config = {
  site_base : string;
  enable_mathjax : bool;
  enable_mermaid : bool;
  enable_lang_toggle : bool;
  languages : string list;
}

(* Build the per-language page list. The dispatcher is responsible
   for loading the article tuples from disk; this function only
   renders them. Tuple = (name, title, body_md). *)
let[@warning "-32"] build_pages ~package_html ~decisions_data ~policy_id ~config
    ~site_pages ~site_pages_ru ~axioms_data =
  let pages = ref [] in

  let render_lang_page lang (name, title, body_md) =
    let page_path = if lang = "ru" then name ^ ".ru.html" else name ^ ".html" in
    let page_title = title ^ " — math-coding" in
    let body_md_parsed = md_parse body_md in
    let body =
      Printf.sprintf "<article class=\"mc-article\">\n%s\n</article>\n"
        body_md_parsed
    in
    {
      path = page_path;
      body =
        render_page ~lang ~page_key:name ~title:page_title ~body
          ~site_base:config.site_base ~enable_mathjax:config.enable_mathjax
          ~enable_mermaid:config.enable_mermaid
          ~enable_lang_toggle:config.enable_lang_toggle ~extra_head:"";
    }
  in

  (* English index *)
  let axioms_overview_html = render_axioms_section axioms_data in
  let index_body_en =
    render_index ~package_html ~axioms_html:axioms_overview_html ~policy_id
  in
  pages :=
    {
      path = "index.html";
      body =
        render_page ~lang:"en" ~page_key:"home" ~title:"math-coding 3.0-alpha"
          ~body:index_body_en ~site_base:config.site_base
          ~enable_mathjax:config.enable_mathjax
          ~enable_mermaid:config.enable_mermaid
          ~enable_lang_toggle:config.enable_lang_toggle ~extra_head:"";
    }
    :: !pages;

  (* Russian index (only when Russian is enabled). *)
  if List.mem "ru" config.languages then begin
    let axioms_overview_html_ru = render_axioms_section axioms_data in
    let index_body_ru =
      render_index_ru ~package_html ~axioms_html:axioms_overview_html_ru
        ~policy_id
    in
    pages :=
      {
        path = "index.ru.html";
        body =
          render_page ~lang:"ru" ~page_key:"home" ~title:"math-coding 3.0-alpha"
            ~body:index_body_ru ~site_base:config.site_base
            ~enable_mathjax:config.enable_mathjax
            ~enable_mermaid:config.enable_mermaid
            ~enable_lang_toggle:config.enable_lang_toggle ~extra_head:"";
      }
      :: !pages
  end;

  (* Per-language articles. *)
  List.iter (fun t -> pages := render_lang_page "en" t :: !pages) site_pages;
  List.iter (fun t -> pages := render_lang_page "ru" t :: !pages) site_pages_ru;

  (* Per-decision pages (English-only). *)
  List.iter
    (fun (decision_id, ob_html) ->
      let body = render_decision_page ~decision_id ~obligation_html:ob_html in
      pages :=
        {
          path = Filename.concat "decisions" (decision_id ^ ".html");
          body =
            render_page ~lang:"en" ~page_key:"packages"
              ~title:(Printf.sprintf "%s — math-coding" decision_id)
              ~body ~site_base:config.site_base
              ~enable_mathjax:config.enable_mathjax
              ~enable_mermaid:config.enable_mermaid
              ~enable_lang_toggle:config.enable_lang_toggle ~extra_head:"";
        }
        :: !pages)
    decisions_data;

  (* Per-axiom pages (English-only — body content is the same). *)
  List.iter
    (fun (axiom_id, body_md) ->
      let body = render_axiom_page ~axiom_id ~body:body_md in
      pages :=
        {
          path = Filename.concat "axioms" (axiom_id ^ ".html");
          body =
            render_page ~lang:"en" ~page_key:"axioms"
              ~title:(Printf.sprintf "Axiom %s" axiom_id)
              ~body ~site_base:config.site_base
              ~enable_mathjax:config.enable_mathjax
              ~enable_mermaid:config.enable_mermaid
              ~enable_lang_toggle:config.enable_lang_toggle ~extra_head:"";
        }
        :: !pages)
    axioms_data;

  List.rev !pages

(* Default configuration used by the CLI. The dispatcher overrides
   from CLI flags. *)
let[@warning "-32"] default_config =
  {
    site_base = "/math-coding/";
    enable_mathjax = true;
    enable_mermaid = true;
    enable_lang_toggle = true;
    languages = [ "en" ];
  }
