(* lib/render.ml — kernel site generator for `mathc render`.
 *
 * The site is generated from three inputs:
 *   1. `decisions/` + `attestations/` (the protocol surface) —
 *      rendered by lib/packages.ml and re-emitted here as the
 *      package grid on index.html and the per-decision pages.
 *   2. `site/*.md` — the prose articles (axioms, methodology,
 *      bootstrap-gate, packages). The articles are written in
 *      a subset of Markdown: headings, paragraphs, lists, code
 *      blocks (incl. `mermaid`), inline code, links, and inline
 *      `^[sidenote]` markers. We deliberately do NOT pull in a
 *      full Markdown library; the protocol's published prose
 *      uses a narrow subset and a 100-line parser is auditable.
 *   3. `site/*.ru.md` (and any future `<name>.<lang>.md`) — the
 *      bilingual siblings. Each English page is rendered twice
 *      (once per available language); each rendering carries
 *      `<html lang="…">` and links to its sibling.
 *
 * The site **demonstrates** the methodology. Every link in
 * the rendered HTML that names a decision points at a per-
 * decision HTML page that is itself generated by this module.
 * The package grid is the HTML form of `mathc packages`. The
 * search index is a flat JSON over the page titles.
 *
 * The render function is pure: it takes a `reader` callback
 * and an `out_dir` string. The dispatcher is the only caller
 * that performs I/O. *)

(* --- minimal Markdown subset --- *)

(* Tiny string-set used by `build_pages` to track which article
   names have a Russian sibling. Implemented as a sorted list of
   strings; for the ≤ 16 entries `site/` carries this is faster
   than pulling in `Set`. *)
module String_set = struct
  type t = string list

  let empty = []

  let rec add x = function
    | [] -> [ x ]
    | y :: rest ->
        if x = y then y :: rest
        else if x < y then x :: y :: rest
        else y :: add x rest

  let rec mem x = function
    | [] -> false
    | y :: rest -> if x = y then true else mem x rest
end

let[@warning "-32"] html_escape s =
  let len = String.length s in
  let buf = Buffer.create len in
  for i = 0 to len - 1 do
    match s.[i] with
    | '<' -> Buffer.add_string buf "&lt;"
    | '>' -> Buffer.add_string buf "&gt;"
    | '&' -> Buffer.add_string buf "&amp;"
    | '"' -> Buffer.add_string buf "&quot;"
    | c -> Buffer.add_char buf c
  done;
  Buffer.contents buf

(* Helper: render the HTML of a list of (html, _) fragments
   by joining all their HTML strings. Used for nested inline
   processing (bold inside bold, link text inside a link). *)
let[@warning "-32"] html_of_fragments (frags : (string * bool) list) : string =
  let buf = Buffer.create 64 in
  List.iter (fun (h, _) -> Buffer.add_string buf h) frags;
  Buffer.contents buf

(* Parse the body of an inline segment looking for `^[text]`
   sidenote syntax. Returns a list of (escaped_html, is_sidenote)
   fragments in source order. Outside a sidenote, also handles
   inline code (`...`). *)
(* Per-render-call sidenote counter. Bumped once per `^[body]`
   occurrence so the inline marker and the margin note share an
   anchor id pair (sn-N, snref-N). The reference itself lives in
   the closure of `loop`; both bindings are introduced inside
   `md_inline_parse`. *)
let[@warning "-32"] rec md_inline_parse s =
  let len = String.length s in
  let buf = Buffer.create len in
  let fragments : (string * bool) list ref = ref [] in
  let sidenote_counter = ref 1 in
  let flush_inline () =
    if Buffer.length buf > 0 then begin
      fragments := (Buffer.contents buf, false) :: !fragments;
      Buffer.clear buf
    end
  in
  let rec loop i =
    if i >= len then flush_inline ()
    else
      let c = s.[i] in
      if c = '`' then begin
        let j = ref (i + 1) in
        while !j < len && s.[!j] <> '`' do
          incr j
        done;
        if !j < len then begin
          let code = String.sub s (i + 1) (!j - i - 1) in
          flush_inline ();
          let html = Printf.sprintf "<code>%s</code>" (html_escape code) in
          fragments := (html, false) :: !fragments;
          loop (!j + 1)
        end
        else begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
      end
      else if c = '^' && i + 1 < len && s.[i + 1] = '[' then begin
        (* sidenote: ^[body] — emit <sup>N</sup> + <label class="sidenote">body</label> *)
        let j = ref (i + 2) in
        let depth = ref 1 in
        while !j < len && !depth > 0 do
          if s.[!j] = '[' then incr depth else if s.[!j] = ']' then decr depth;
          if !depth > 0 then incr j
        done;
        if !j < len && !depth = 0 then begin
          let body_str = String.sub s (i + 2) (!j - i - 2) in
          flush_inline ();
          let n = !sidenote_counter in
          let marker =
            Printf.sprintf
              "<sup><a id=\"snref-%d\" href=\"#sn-%d\" \
               class=\"sidenote-number\">%d</a></sup>"
              n n n
          in
          let sidenote_html =
            Printf.sprintf
              "<label for=\"snref-%d\" class=\"sidenote\" \
               id=\"sn-%d\">%s</label>"
              n n (html_escape body_str)
          in
          fragments := (sidenote_html, true) :: (marker, true) :: !fragments;
          incr sidenote_counter;
          loop (!j + 1)
        end
        else begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
      end
      else if c = '*' && i + 1 < len && s.[i + 1] = '*' then begin
        (* Bold: **text** → <strong>text</strong> *)
        let k = ref (i + 2) in
        let found = ref false in
        let body_start = i + 2 in
        let body_end = ref body_start in
        while !k + 1 < len && not !found do
          if s.[!k] = '*' && s.[!k + 1] = '*' then begin
            body_end := !k;
            found := true
          end
          else incr k
        done;
        if !found then begin
          flush_inline ();
          let body_str = String.sub s body_start (!body_end - body_start) in
          let html =
            Printf.sprintf "<strong>%s</strong>"
              (html_of_fragments (md_inline_parse body_str))
          in
          fragments := (html, false) :: !fragments;
          loop (!k + 2)
        end
        else begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
      end
      else if c = '*' then begin
        (* Italic: *text* → <em>text</em>. Tolerant: any non-empty
           body not containing a literal `*` works. Lone asterisk
           without a closing match stays literal. *)
        let k = ref (i + 1) in
        let found = ref false in
        let body_start = i + 1 in
        let body_end = ref body_start in
        while !k < len && not !found do
          if s.[!k] = '*' then begin
            body_end := !k;
            found := true
          end
          else incr k
        done;
        if !found && !body_end > body_start then begin
          flush_inline ();
          let body_str = String.sub s body_start (!body_end - body_start) in
          let html =
            Printf.sprintf "<em>%s</em>"
              (html_of_fragments (md_inline_parse body_str))
          in
          fragments := (html, false) :: !fragments;
          loop (!k + 1)
        end
        else begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
      end
      else if c = '_' && i + 1 < len && s.[i + 1] <> '_' then begin
        (* Italic via underscore: _text_ → <em>text</em>. Word-
           boundary rule: the opener must be preceded by whitespace
           or string start, AND the body must not start with an
           alphanumeric (so identifiers like `foo_bar` are not
           italicised). This matches CommonMark's "intraword
           underscore" exception and keeps `$x_i$` safe. *)
        let prev_char_ok =
          i = 0
          ||
          let pc = s.[i - 1] in
          pc = ' ' || pc = '\n' || pc = '\t' || pc = '\r'
        in
        if not prev_char_ok then begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
        else begin
          let k = ref (i + 1) in
          let found = ref false in
          let body_start = i + 1 in
          let body_end = ref body_start in
          while !k < len && not !found do
            if s.[!k] = '_' then begin
              let next_idx = !k + 1 in
              let next_ok =
                next_idx >= len
                ||
                let nc = s.[next_idx] in
                nc = ' ' || nc = '\n' || nc = '\t' || nc = '\r' || nc = '.'
                || nc = ',' || nc = ';' || nc = ':' || nc = '!' || nc = '?'
                || nc = ')'
              in
              if next_ok then begin
                body_end := !k;
                found := true
              end
              else incr k
            end
            else incr k
          done;
          if !found && !body_end > body_start then begin
            flush_inline ();
            let body_str = String.sub s body_start (!body_end - body_start) in
            let html =
              Printf.sprintf "<em>%s</em>"
                (html_of_fragments (md_inline_parse body_str))
            in
            fragments := (html, false) :: !fragments;
            loop (!k + 1)
          end
          else begin
            Buffer.add_char buf c;
            loop (i + 1)
          end
        end
      end
      else if c = '[' then begin
        (* Inline link: [text](url). Tolerant: if no `]` followed by
           `(` is found, the `[` is literal. *)
        let k = ref (i + 1) in
        let depth = ref 1 in
        let found_text = ref false in
        let text_end = ref 0 in
        while !k < len && not !found_text do
          if s.[!k] = '[' then incr depth
          else if s.[!k] = ']' then begin
            decr depth;
            if !depth = 0 then begin
              text_end := !k;
              found_text := true
            end
          end;
          if not !found_text then incr k
        done;
        if !found_text && !text_end + 1 < len && s.[!text_end + 1] = '(' then begin
          let m = ref (!text_end + 2) in
          let depth_p = ref 1 in
          let url_end = ref 0 in
          let found_url = ref false in
          while !m < len && not !found_url do
            if s.[!m] = '(' then incr depth_p
            else if s.[!m] = ')' then begin
              decr depth_p;
              if !depth_p = 0 then begin
                url_end := !m;
                found_url := true
              end
            end;
            if not !found_url then incr m
          done;
          if !found_url then begin
            let text = String.sub s (i + 1) (!text_end - i - 1) in
            let url =
              String.trim
                (String.sub s (!text_end + 2) (!url_end - !text_end - 2))
            in
            flush_inline ();
            let html =
              Printf.sprintf "<a href=\"%s\">%s</a>" (html_escape url)
                (html_of_fragments (md_inline_parse text))
            in
            fragments := (html, false) :: !fragments;
            loop (!url_end + 1)
          end
          else begin
            Buffer.add_char buf c;
            loop (i + 1)
          end
        end
        else begin
          Buffer.add_char buf c;
          loop (i + 1)
        end
      end
      else begin
        Buffer.add_char buf c;
        loop (i + 1)
      end
  in
  loop 0;
  List.rev !fragments

(* Wrap a list of (html_fragment, is_sidenote) into the final
   inline HTML: pure-text fragments get md_inline (which handles
   backtick code), sidenote fragments are emitted verbatim. *)
let[@warning "-32"] md_inline s =
  let frags = md_inline_parse s in
  let buf = Buffer.create (String.length s) in
  List.iter
    (fun (html, is_sn) ->
      if is_sn then Buffer.add_string buf html else Buffer.add_string buf html)
    frags;
  Buffer.contents buf

(* Detect the language tag on a fenced code block. The line is
   `\`\`\`TAG`. Returns Some TAG if the tag is meaningful
   (anything but the empty string), else None. *)
let[@warning "-32"] code_fence_tag (line : string) : string option =
  let t = String.trim line in
  if String.length t > 3 && String.sub t 0 3 = "```" then begin
    let rest = String.sub t 3 (String.length t - 3) in
    let lang = String.trim rest in
    if lang = "" then None else Some lang
  end
  else None

let[@warning "-32"] md_parse source =
  let lines = String.split_on_char '\n' source in
  let buf = Buffer.create 256 in
  let flush_para text =
    if text <> "" then begin
      Buffer.add_string buf "  <p>";
      Buffer.add_string buf (html_of_fragments (md_inline_parse text));
      Buffer.add_string buf "</p>\n"
    end
  in
  let rec collect_code acc = function
    | [] -> (List.rev acc, [])
    | l :: r ->
        let trimmed = String.trim l in
        (* Closing fence is at least 3 backticks (CommonMark allows
           longer, but our subset honours the minimum). Length check
           is `>= 3` (not `> 4`) — the previous form silently missed
           a 3-char "```" because "```" has length 3 but `String.sub
           "```" 0 4` raised Invalid_argument on the unguarded form;
           the `> 4` guard hid the bug behind "matches too few
           lines". *)
        if String.length trimmed >= 3 && String.sub trimmed 0 3 = "```" then
          (List.rev acc, r)
        else collect_code (l :: acc) r
  in
  (* Detect whether a line is a horizontal rule: dashes or
     asterisks only. Used by md_parse. *)
  let[@warning "-32"] is_hr_line t =
    if String.length t < 3 then false
    else
      let c0 = t.[0] in
      (c0 = '-' || c0 = '*') && String.for_all (fun c -> c = c0) t
  in
  (* Detect whether a line starts a markdown table row.
     The line must start with `|`. *)
  let[@warning "-32"] is_table_line t = String.length t > 0 && t.[0] = '|' in
  (* A line is a table separator when it consists solely of
     `|`, `-`, `:`, and whitespace. *)
  let[@warning "-32"] is_table_separator t =
    String.length t > 2
    && String.contains t '|' && String.contains t '-'
    && String.for_all (fun c -> c = '|' || c = '-' || c = ':' || c = ' ') t
  in
  (* Split a table row by `|`, dropping the leading/trailing
     empty cell when the row starts or ends with `|`. *)
  let[@warning "-32"] split_table_row t =
    let len = String.length t in
    if len = 0 then []
    else
      let start = if t.[0] = '|' then 1 else 0 in
      let finish = if t.[len - 1] = '|' then len - 1 else len in
      let cells = ref [] in
      let i = ref start in
      while !i < finish do
        let j = ref !i in
        while !j < finish && t.[!j] <> '|' do
          incr j
        done;
        let cell = String.trim (String.sub t !i (!j - !i)) in
        cells := cell :: !cells;
        i := !j + 1
      done;
      List.rev !cells
  in
  let render_table header_rows body_rows =
    Buffer.add_string buf "<table class=\"mathc-table\">\n";
    if header_rows <> [] then begin
      Buffer.add_string buf "  <thead>\n  <tr>";
      List.iter
        (fun cell ->
          Buffer.add_string buf "<th>";
          Buffer.add_string buf (html_of_fragments (md_inline_parse cell));
          Buffer.add_string buf "</th>")
        header_rows;
      Buffer.add_string buf "</tr>\n  </thead>\n"
    end;
    if body_rows <> [] then begin
      Buffer.add_string buf "  <tbody>\n";
      List.iter
        (fun row ->
          Buffer.add_string buf "    <tr>";
          List.iter
            (fun cell ->
              Buffer.add_string buf "<td>";
              Buffer.add_string buf (html_of_fragments (md_inline_parse cell));
              Buffer.add_string buf "</td>")
            row;
          Buffer.add_string buf "</tr>\n")
        body_rows;
      Buffer.add_string buf "  </tbody>\n"
    end;
    Buffer.add_string buf "</table>\n"
  in
  (* Collect subsequent table rows until a blank line or non-table line. *)
  let collect_table_rows rem =
    let rec loop acc = function
      | [] -> (List.rev acc, [])
      | line :: more ->
          let t = String.trim line in
          if t = "" then (List.rev acc, more)
          else if is_table_line t then loop (split_table_row t :: acc) more
          else (List.rev acc, line :: more)
    in
    loop [] rem
  in
  let rec loop acc_para = function
    | [] -> flush_para acc_para
    | line :: rest -> (
        let t = String.trim line in
        let push_para () = flush_para acc_para in
        match t with
        | "" ->
            push_para ();
            loop "" rest
        | _ when String.length t > 2 && String.sub t 0 2 = "# " ->
            push_para ();
            Buffer.add_string buf "<h1>";
            Buffer.add_string buf
              (md_inline (String.sub t 2 (String.length t - 2)));
            Buffer.add_string buf "</h1>\n";
            loop "" rest
        | _ when String.length t > 3 && String.sub t 0 3 = "## " ->
            push_para ();
            Buffer.add_string buf "<h2>";
            Buffer.add_string buf
              (md_inline (String.sub t 3 (String.length t - 3)));
            Buffer.add_string buf "</h2>\n";
            loop "" rest
        | _ when String.length t > 4 && String.sub t 0 4 = "### " ->
            push_para ();
            Buffer.add_string buf "<h3>";
            Buffer.add_string buf
              (md_inline (String.sub t 4 (String.length t - 4)));
            Buffer.add_string buf "</h3>\n";
            loop "" rest
        | _ when String.length t >= 3 && String.sub t 0 3 = "```" -> begin
            push_para ();
            let tag = code_fence_tag line in
            let collected, after = collect_code [] rest in
            let code = String.concat "\n" collected in
            (match tag with
            | Some "mermaid" ->
                Buffer.add_string buf "<div class=\"mermaid\">";
                Buffer.add_string buf (html_escape code);
                Buffer.add_string buf "</div>\n"
            | Some lang ->
                Buffer.add_string buf "<pre><code class=\"language-";
                Buffer.add_string buf (html_escape lang);
                Buffer.add_string buf "\">";
                Buffer.add_string buf (html_escape code);
                Buffer.add_string buf "</code></pre>\n"
            | None ->
                Buffer.add_string buf "<pre><code>";
                Buffer.add_string buf (html_escape code);
                Buffer.add_string buf "</code></pre>\n");
            loop "" after
          end
        | _ when is_hr_line t ->
            push_para ();
            Buffer.add_string buf "<hr>\n";
            loop "" rest
        | _ when String.length t > 1 && t.[0] = '>' ->
            push_para ();
            (* Blockquote: each `> ` line joins the quote body. The
               FIRST line's body is taken from `t` (the matched line);
               subsequent lines contribute their own body via
               collect's recursive body extraction. *)
            let first_body =
              String.trim (String.sub t 1 (String.length t - 1))
            in
            let rec collect acc rem =
              match rem with
              | [] -> (acc, [])
              | l :: r ->
                  let tt = String.trim l in
                  if String.length tt > 0 && tt.[0] = '>' then
                    let b =
                      String.trim (String.sub tt 1 (String.length tt - 1))
                    in
                    collect (b :: acc) r
                  else (acc, l :: r)
            in
            let collected, after = collect [ first_body ] rest in
            let joined = String.concat " " (List.rev collected) in
            Buffer.add_string buf "<blockquote><p>";
            Buffer.add_string buf (html_of_fragments (md_inline_parse joined));
            Buffer.add_string buf "</p></blockquote>\n";
            loop "" after
        | _ when is_table_line t && String.length t > 2 -> (
            push_para ();
            (* Detect table: header | separator | row* | blank. *)
            let header_cells = split_table_row t in
            match rest with
            | sep :: rows when is_table_separator (String.trim sep) ->
                let body_rows, after = collect_table_rows rows in
                render_table header_cells body_rows;
                loop "" after
            | _ ->
                (* Not a table; emit as paragraph *)
                let next = if acc_para = "" then t else acc_para ^ " " ^ t in
                loop next rest)
        | _ when String.length t > 2 && String.sub t 0 2 = "- " ->
            push_para ();
            Buffer.add_string buf "<ul>\n";
            (* Collect a multi-line list: each `- ` line starts a new
               item; subsequent non-blank lines that are NOT new list
               markers / headings / fences / hr / blockquote are joined
               into the previous item with a single space. This is the
               "tight list with single-line continuation" used by all
               `site/*.md` and `axioms/*.md` content; we do not honour
               the indented-2-space hard-break rule (CommonMark §6). *)
            let is_new_item_line tt =
              String.length tt > 2 && String.sub tt 0 2 = "- "
            in
            let is_block_starter tt =
              (* Anything that ends the list entirely. *)
              (String.length tt >= 3 && String.sub tt 0 3 = "```")
              || (String.length tt > 2 && String.sub tt 0 2 = "# ")
              || (String.length tt > 3 && String.sub tt 0 3 = "## ")
              || (String.length tt > 4 && String.sub tt 0 4 = "### ")
              || (String.length tt > 0 && tt.[0] = '>')
              || is_hr_line tt
              || (String.length tt > 0 && tt.[0] = '|')
            in
            (* items_rev: list of (item_lines list) in reverse; the
               first item_lines list is the lines of the FIRST item
               currently being built (its first line is `line`). *)
            let rec collect items_rev current_item rem =
              match rem with
              | [] -> (List.rev items_rev, List.rev current_item, [])
              | l :: r ->
                  let tt = String.trim l in
                  if tt = "" then
                    (List.rev items_rev, List.rev current_item, l :: r)
                  else if is_new_item_line tt then begin
                    let finished = List.rev current_item in
                    collect ([ finished ] @ items_rev)
                      [ String.sub tt 2 (String.length tt - 2) ]
                      r
                  end
                  else if is_block_starter tt then
                    (List.rev items_rev, List.rev current_item, l :: r)
                  else collect items_rev (l :: current_item) r
            in
            let first_body = String.sub t 2 (String.length t - 2) in
            let items, current, after = collect [] [ first_body ] rest in
            let all_items =
              match current with [] -> items | _ -> items @ [ current ]
            in
            List.iter
              (fun item_lines ->
                let joined =
                  String.concat " "
                    (List.map (fun s -> String.trim s) item_lines)
                in
                Buffer.add_string buf "  <li>";
                Buffer.add_string buf (md_inline joined);
                Buffer.add_string buf "</li>\n")
              all_items;
            Buffer.add_string buf "</ul>\n";
            loop "" after
        | _ ->
            let next = if acc_para = "" then t else acc_para ^ " " ^ t in
            loop next rest)
  in
  loop "" lines;
  Buffer.contents buf

(* --- navigation --- *)

(* The site's English navigation. Every key also has a Russian
   counterpart when the corresponding site/<key>.ru.md exists.
   The dispatcher decides which languages to render; this list
   is the union of all available pages. *)
let[@warning "-32"] nav_links_en =
  [
    ("home", "Home", "index.html");
    ("axioms", "Axioms", "axioms.html");
    ("manifesto", "Manifesto", "manifesto.html");
    ("foundations", "Foundations", "foundations.html");
    ("methodology", "Methodology", "methodology.html");
    ("workflow", "Workflow", "workflow.html");
    ("faq", "FAQ", "faq.html");
    ("readme", "README", "readme.html");
    ("contributing", "Contributing", "contributing.html");
    ("bootstrap-gate", "Bootstrap Gate", "bootstrap-gate.html");
    ("packages", "Packages", "packages.html");
  ]

let[@warning "-32"] nav_links_ru =
  [
    ("home", "Главная", "index.html");
    ("axioms", "Аксиомы", "axioms.html");
    ("manifesto", "Манифест", "manifesto.ru.html");
    ("foundations", "Основания", "foundations.ru.html");
    ("methodology", "Методология", "methodology.html");
    ("workflow", "Workflow", "workflow.html");
    ("faq", "FAQ", "faq.html");
    ("readme", "README", "readme.ru.html");
    ("contributing", "Contributing", "contributing.html");
    ("bootstrap-gate", "Bootstrap-ворота", "bootstrap-gate.html");
    ("packages", "Пакеты", "packages.html");
  ]

let[@warning "-32"] nav_links_for lang =
  if lang = "ru" then nav_links_ru else nav_links_en

let[@warning "-32"] sibling_translation_href ~lang ~page_key ~has_ru =
  (* Each English page links to its Russian sibling and vice versa.
     If only one translation exists, the link is omitted. The
     caller passes `has_ru` from `build_pages`, which knows whether
     the Russian source `site/<name>.ru.md` exists. The previous
     unconditional `Some (...)` returned a `<name>.ru.html` URL
     that 404'd for methodology / workflow / faq — visible defect
     in the audit on 2026-10-07. *)
  match lang with
  | "ru" -> Some (page_key ^ ".html") (* Russian -> English default *)
  | _ when page_key = "home" -> if has_ru then Some "index.ru.html" else None
  | _ -> if has_ru then Some (page_key ^ ".ru.html") else None

let[@warning "-32"] render_nav ~lang ~page_key ~enable_lang_toggle ~has_ru =
  let buf = Buffer.create 256 in
  let links = nav_links_for lang in
  Buffer.add_string buf "<nav class=\"site-nav\">\n";
  Buffer.add_string buf "  <a class=\"brand\" href=\"./\">math-coding</a>\n";
  Buffer.add_string buf
    "  <button type=\"button\" class=\"nav-toggle\" aria-label=\"Toggle \
     navigation\" aria-controls=\"nav-inner\" aria-expanded=\"false\"><span \
     aria-hidden=\"true\">&#9776;</span></button>\n";
  Buffer.add_string buf "  <ul class=\"nav-inner\" id=\"nav-inner\">\n";
  List.iter
    (fun (key, label, href) ->
      let cls =
        if key = page_key then " class=\"nav-link active\""
        else " class=\"nav-link\""
      in
      Printf.bprintf buf "    <li><a%s href=\"%s\">%s</a></li>\n" cls href label)
    links;
  Buffer.add_string buf "  </ul>\n";
  (if enable_lang_toggle then
     match sibling_translation_href ~lang ~page_key ~has_ru with
     | Some h ->
         let other_lang = if lang = "ru" then "en" else "ru" in
         let other_label = if lang = "ru" then "EN" else "RU" in
         Printf.bprintf buf
           "  <a class=\"lang-toggle\" href=\"%s\" hreflang=\"%s\" \
            lang=\"%s\">%s</a>\n"
           h other_lang other_lang other_label
     | None -> ());
  Buffer.add_string buf "</nav>\n";
  Buffer.contents buf

(* --- footer --- *)

let[@warning "-32"] render_footer ~lang ~version =
  (* The footer always carries the live project version so a viewer
     who lands on the site can tell which build is live. The string
     is whatever was passed via `config.version` — by default
     this is the contents of the `VERSION` file at render-time. *)
  let site_meta =
    if lang = "ru" then
      Printf.sprintf
        "<p class=\"site-meta\">%s &middot; <a \
         href=\"../AGENTS.html\">AGENTS.md</a> &middot; <a \
         href=\"../ROADMAP.html\">ROADMAP.md</a> &middot; <a \
         href=\"../PACKAGES.html\">PACKAGES.md</a> &middot; <a \
         href=\"index.html\">EN</a></p>\n"
        (html_escape version)
    else
      Printf.sprintf
        "<p class=\"site-meta\">%s &middot; <a \
         href=\"../AGENTS.html\">AGENTS.md</a> &middot; <a \
         href=\"../ROADMAP.html\">ROADMAP.md</a> &middot; <a \
         href=\"../PACKAGES.html\">PACKAGES.md</a> &middot; <a \
         href=\"index.ru.html\">RU</a></p>\n"
        (html_escape version)
  in
  Printf.sprintf
    "<footer class=\"site-footer\">\n\
     <p>Built by <code>mathc render</code> at build time. The site follows the \
     math-coding methodology: every page that describes a kernel feature is \
     itself produced by the kernel.</p>\n\
     %s</footer>\n"
    site_meta

(* --- page renderer --- *)

(* `<head>` carries: charset, viewport, <base href>, title, the
   stylesheet, optional MathJax script, optional mermaid script,
   and any caller-supplied extra head. *)
let[@warning "-32"] render_head ~lang ~site_base ~title ~enable_mathjax
    ~enable_mermaid ~extra_head =
  let buf = Buffer.create 256 in
  Printf.bprintf buf "<meta charset=\"utf-8\">\n";
  Printf.bprintf buf
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
  if site_base <> "" then
    Printf.bprintf buf "<base href=\"%s\">\n" (html_escape site_base);
  Printf.bprintf buf "<title>%s &mdash; math-coding</title>\n"
    (html_escape title);
  Printf.bprintf buf "<link rel=\"stylesheet\" href=\"assets/style.css\">\n";
  if enable_mathjax then begin
    Printf.bprintf buf
      "<script defer \
       src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n";
    Printf.bprintf buf
      "<script>\n\
       window.MathJax = { tex: { inlineMath: [['\\(','\\)'], ['$','$']], \
       displayMath: [['$$','$$'], ['\\[','\\]']] } };\n\
       </script>\n"
  end;
  if enable_mermaid then begin
    Printf.bprintf buf
      "<script defer \
       src=\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js\"></script>\n";
    Printf.bprintf buf
      "<script>\n\
       document.addEventListener('DOMContentLoaded', function () { if \
       (window.mermaid) mermaid.initialize({startOnLoad: true}); });\n\
       </script>\n"
  end;
  if extra_head <> "" then Printf.bprintf buf "%s\n" extra_head;
  Buffer.contents buf

let[@warning "-32"] render_page ~lang ~page_key ~title ~body ~site_base
    ~enable_mathjax ~enable_mermaid ~enable_lang_toggle ~has_ru ~version
    ~extra_head =
  let head =
    render_head ~lang ~site_base ~title ~enable_mathjax ~enable_mermaid
      ~extra_head
  in
  Printf.sprintf
    "<!DOCTYPE html>\n\
     <html lang=\"%s\">\n\
     <head>\n\
     %s</head>\n\
     <body>\n\
     %s\n\
     <main class=\"site-main\">\n\
     %s\n\
     </main>\n\
     %s\n\
     <script>\n\
     (function(){\n\
     var t = document.querySelector('.nav-toggle');\n\
     var n = document.querySelector('.nav-inner');\n\
     if (!t || !n) return;\n\
     function sync(){\n\
     var isMobile = window.matchMedia('(max-width: 760px)').matches;\n\
     if (isMobile) { t.style.display = 'block'; }\n\
     else { t.style.display = 'none'; t.setAttribute('aria-expanded','false'); \
     n.style.display = 'flex'; }\n\
     }\n\
     sync();\n\
     window.addEventListener('resize', sync);\n\
     t.addEventListener('click', function(){\n\
     var open = t.getAttribute('aria-expanded') === 'true';\n\
     t.setAttribute('aria-expanded', open ? 'false' : 'true');\n\
     n.style.display = open ? 'none' : 'flex';\n\
     });\n\
     })();\n\
     </script>\n\
     </body>\n\
     </html>\n"
    lang head
    (render_nav ~lang ~page_key ~enable_lang_toggle ~has_ru)
    body
    (render_footer ~lang ~version)

let[@warning "-32"] render_axioms_section axioms =
  let buf = Buffer.create 256 in
  Buffer.add_string buf "<section class=\"mathc-axioms\">\n";
  List.iter
    (fun (id, body) ->
      Printf.bprintf buf
        "<article class=\"mathc-axiom\">\n\
         <h2>%s</h2>\n\
         <div>%s</div>\n\
         </article>\n"
        (html_escape id) (md_parse body))
    axioms;
  Buffer.add_string buf "</section>\n";
  Buffer.contents buf

let[@warning "-32"] render_index ~package_html ~axioms_html ~policy_id ~version
    =
  Printf.sprintf
    "<section class=\"hero\">\n\
     <h1>math-coding %s</h1>\n\
     <p class=\"lead\">A risk-adaptive assurance protocol for software \
     changes. Links <em>intent</em>, <em>decisions</em>, <em>obligations</em>, \
     <em>changes</em>, <em>attestations</em>, and <em>revisions</em> into a \
     single traceable chain. The site you are reading was built by the same \
     kernel that the protocol describes.</p>\n\
     <p class=\"meta\">Active policy: <code>%s</code>. The package grid below \
     is the live output of <code>mathc packages --format=html</code>.</p>\n\
     </section>\n\
     <section class=\"mathc-packages-section\">\n\
     <h2>Packages</h2>\n\
     %s\n\
     </section>\n\
     <section class=\"mathc-axioms-section\">\n\
     <h2>Axioms</h2>\n\
     %s\n\
     </section>\n\
     <p class=\"site-callout\">Every page on this site is produced by the \
     math-coding kernel. The methodology is the artifact; the artifact follows \
     the methodology.</p>\n"
    (html_escape version) (html_escape policy_id) package_html axioms_html

let[@warning "-32"] render_index_ru ~package_html ~axioms_html ~policy_id
    ~version =
  Printf.sprintf
    "<section class=\"hero\">\n\
     <h1>math-coding %s</h1>\n\
     <p class=\"lead\">Протокол assurance для изменений в программном \
     обеспечении, адаптированный к риску. Связывает <em>intent</em>, \
     <em>decisions</em>, <em>obligations</em>, <em>changes</em>, \
     <em>attestations</em> и <em>revisions</em> в одну прослеживаемую цепочку. \
     Сайт, который вы читаете, построен тем же ядром, которое описывает \
     протокол.</p>\n\
     <p class=\"meta\">Активная политика: <code>%s</code>. Сетка пакетов ниже \
     — живой вывод <code>mathc packages --format=html</code>.</p>\n\
     </section>\n\
     <section class=\"mathc-packages-section\">\n\
     <h2>Пакеты</h2>\n\
     %s\n\
     </section>\n\
     <section class=\"mathc-axioms-section\">\n\
     <h2>Аксиомы</h2>\n\
     %s\n\
     </section>\n\
     <p class=\"site-callout\">Каждая страница этого сайта создаётся ядром \
     math-coding. Методология есть артефакт; артефакт следует методологии.</p>\n"
    (html_escape version) (html_escape policy_id) package_html axioms_html

let[@warning "-32"] render_decision_page ~decision_id ~obligation_html =
  Printf.sprintf
    "<section class=\"mathc-decision-page\">\n<h1>%s</h1>\n%s\n</section>\n"
    decision_id obligation_html

let[@warning "-32"] render_spec_page ~name ~body_md =
  (* `spec/<name>.md` pages — normative algebra-3.2 spec, the
     constitution, the domain, the semantics. Each page is rendered
     with `enable_mathjax:true` so MathJax 3 (in defer mode) is
     injected into `<head>` and the page's `$..$` / `$$..$$`
     formulas are typeset as TeX at runtime. The class
     `mathc-spec-page` marks the wrapper so a future stylesheet
     can target math-heavy spec pages distinctly from prose site
     articles. *)
  let body_md_parsed = md_parse body_md in
  Printf.sprintf "<section class=\"mathc-spec-page\">\n%s\n</section>\n"
    body_md_parsed

let[@warning "-32"] render_axiom_page ~axiom_id ~body =
  (* If the source body starts with `# <title>`, strip that
     leading heading — the synthetic `<h1>Axiom <id></h1>` we
     emit is the only heading the page needs. Without this
     strip, every per-axiom page carries two `<h1>` (e.g. on
     `dist/axioms/feedback.html`: "Axiom feedback" from the
     template + "Axiom A1 — Feedback" from the source). *)
  let stripped_body =
    let trimmed = String.trim body in
    let len = String.length trimmed in
    if len > 2 && String.sub trimmed 0 2 = "# " then begin
      let prefix_len = 2 in
      let after_hash = String.sub trimmed prefix_len (len - prefix_len) in
      let nl_in_after =
        let s = String.length after_hash in
        let i = ref 0 in
        while !i < s && after_hash.[!i] <> '\n' do
          incr i
        done;
        if !i = s then s else !i
      in
      let first_line = String.sub after_hash 0 nl_in_after in
      (* `rest_start` is an offset into `trimmed`; convert it back to
         an offset into the original `body` by adding the leading
         whitespace count. *)
      let ws = ref 0 in
      while
        !ws < String.length body && (body.[!ws] = ' ' || body.[!ws] = '\n')
      do
        incr ws
      done;
      let rest_start_in_body = !ws + prefix_len + nl_in_after + 1 in
      let rest =
        if rest_start_in_body < String.length body then
          String.sub body rest_start_in_body
            (String.length body - rest_start_in_body)
        else ""
      in
      String.trim (Printf.sprintf "%s\n%s" first_line rest)
    end
    else body
  in
  Printf.sprintf
    "<section class=\"mathc-axiom-page\">\n\
     <h1>Axiom %s</h1>\n\
     <div>%s</div>\n\
     </section>\n"
    axiom_id (md_parse stripped_body)

(* --- render entry point --- *)

type page = { path : string; body : string }

(* Configuration bag passed by the dispatcher. *)
type config = {
  site_base : string;
  enable_mathjax : bool;
  enable_mermaid : bool;
  enable_lang_toggle : bool;
  languages : string list;
  version : string;
}

(* Read the project version from a `VERSION` file. The file is the
   single source of truth — release procedure writes it (or a
   pre-commit hook keeps it in sync with the latest `v*` tag). We
   try a small set of well-known paths because the CWD at module
   load time is not always the repo root (it is, in the `mathc
   render` invocation pattern; it is not, when the test harness
   loads the kernel from `_build/default/tests/`). The `fallback`
   argument is used when none of the candidates exist, so the
   kernel does not crash on a clean install where the share-dir
   VERSION is elsewhere. *)
let[@warning "-32"] read_version_file ~fallback =
  (* `dune test` exports the project root in `DUNE_SOURCEROOT`;
     honour it first so test runs and `mathc render` invocations
     agree on the same VERSION file. *)
  let dune_root =
    match Sys.getenv_opt "DUNE_SOURCEROOT" with
    | Some p -> Some (Filename.concat p "VERSION")
    | None -> None
  in
  let candidates =
    Option.to_list dune_root
    @ [
        "VERSION";
        "../VERSION";
        "../../VERSION";
        "../../../VERSION";
        "../../../../VERSION";
      ]
  in
  let try_one path =
    if Sys.file_exists path then begin
      let ic = open_in path in
      let n = in_channel_length ic in
      let s = really_input_string ic n in
      close_in ic;
      Some (s |> String.trim)
    end
    else None
  in
  let rec loop = function
    | [] -> fallback
    | p :: rest -> ( match try_one p with Some v -> v | None -> loop rest)
  in
  loop candidates

(* Read every `*.md` file under `spec/` and return them as
   (name, body) pairs sorted alphabetically. The dispatcher
   did not previously render spec files; this helper lets
   `build_pages` self-serve the spec source so a spec page
   lands under `dist/spec/<name>.html` with MathJax 3 in
   `<head>`, without requiring a dispatcher change. The read
   is best-effort: a missing `spec/` directory or unreadable
   file returns `[]`, matching `read_axioms` in `bin/Mathc.ml`.
   `DUNE_SOURCEROOT` is honoured first so a kernel test
   loaded from `_build/default/tests/` reads the same `spec/`
   that a `mathc render` invocation does. *)
let[@warning "-32"] read_spec_files () =
  let candidates =
    match Sys.getenv_opt "DUNE_SOURCEROOT" with
    | Some p -> [ Filename.concat p "spec" ]
    | None -> []
  in
  let candidates = candidates @ [ "spec" ] in
  let try_dir d =
    if not (Sys.file_exists d) then None
    else if not (Sys.is_directory d) then None
    else
      try
        Some
          (Sys.readdir d |> Array.to_list
          |> List.filter (fun n -> Filename.extension n = ".md")
          |> List.sort String.compare
          |> List.filter_map (fun n ->
              let base = Filename.chop_extension n in
              let path = Filename.concat d n in
              let ic = open_in_bin path in
              let n_bytes = in_channel_length ic in
              let s =
                if n_bytes = 0 then "" else really_input_string ic n_bytes
              in
              close_in ic;
              if s = "" then None else Some (base, s)))
      with _ -> None
  in
  let rec loop = function
    | [] -> []
    | d :: rest -> ( match try_dir d with Some xs -> xs | None -> loop rest)
  in
  loop candidates

(* Default version used when no VERSION file is present. Kept
   conservative — a render with an explicit version string
   (e.g., `v3.1.0-alpha`) is preferred so a viewer who lands on
   the site mid-release can tell which build is live. *)
let[@warning "-32"] default_version = "math-coding"

(* Build the per-language page list. The dispatcher is responsible
   for loading the article tuples from disk; this function only
   renders them. Tuple = (name, title, body_md). *)
let[@warning "-32"] build_pages ~package_html ~decisions_data ~policy_id ~config
    ~site_pages ~site_pages_ru ~axioms_data =
  let pages = ref [] in
  let version = config.version in

  (* Set of `name` keys that have a Russian sibling. Used by the
     language toggle to decide whether to emit `<name>.ru.html`
     link. Built once from `site_pages_ru`. *)
  let ru_keys =
    List.fold_left
      (fun acc (name, _, _) -> String_set.add name acc)
      String_set.empty site_pages_ru
  in
  let has_ru name = String_set.mem name ru_keys in

  let render_lang_page lang (name, title, body_md) =
    let page_path = if lang = "ru" then name ^ ".ru.html" else name ^ ".html" in
    let page_title = title ^ " — math-coding" in
    let body_md_parsed = md_parse body_md in
    (* The `packages` page appends the live kernel package grid
       below the prose. The grid is the same HTML that
       `mathc packages --format=html` emits; embedding it here
       means `dist/packages.html` is no longer prose-only. *)
    let body_extra =
      if name = "packages" then
        Printf.sprintf
          "\n\
           <section class=\"mathc-packages-section\">\n\
           <h2>Packages</h2>\n\
           %s\n\
           </section>\n"
          package_html
      else ""
    in
    let body =
      Printf.sprintf "<article class=\"mathc-article\">\n%s%s\n</article>\n"
        body_md_parsed body_extra
    in
    {
      path = page_path;
      body =
        render_page ~lang ~page_key:name ~title:page_title ~body
          ~site_base:config.site_base ~enable_mathjax:config.enable_mathjax
          ~enable_mermaid:config.enable_mermaid
          ~enable_lang_toggle:config.enable_lang_toggle ~has_ru:(has_ru name)
          ~version ~extra_head:"";
    }
  in

  (* English index *)
  let axioms_overview_html = render_axioms_section axioms_data in
  let index_body_en =
    render_index ~package_html ~axioms_html:axioms_overview_html ~policy_id
      ~version
  in
  pages :=
    {
      path = "index.html";
      body =
        render_page ~lang:"en" ~page_key:"home"
          ~title:(Printf.sprintf "math-coding %s" version)
          ~body:index_body_en ~site_base:config.site_base
          ~enable_mathjax:config.enable_mathjax
          ~enable_mermaid:config.enable_mermaid
          ~enable_lang_toggle:config.enable_lang_toggle ~has_ru:(has_ru "home")
          ~version ~extra_head:"";
    }
    :: !pages;

  (* Russian index (only when Russian is enabled). *)
  if List.mem "ru" config.languages then begin
    let axioms_overview_html_ru = render_axioms_section axioms_data in
    let index_body_ru =
      render_index_ru ~package_html ~axioms_html:axioms_overview_html_ru
        ~policy_id ~version
    in
    pages :=
      {
        path = "index.ru.html";
        body =
          render_page ~lang:"ru" ~page_key:"home"
            ~title:(Printf.sprintf "math-coding %s" version)
            ~body:index_body_ru ~site_base:config.site_base
            ~enable_mathjax:config.enable_mathjax
            ~enable_mermaid:config.enable_mermaid
            ~enable_lang_toggle:config.enable_lang_toggle
            ~has_ru:(has_ru "home") ~version ~extra_head:"";
      }
      :: !pages
  end;

  (* Per-language articles. *)
  List.iter (fun t -> pages := render_lang_page "en" t :: !pages) site_pages;
  List.iter (fun t -> pages := render_lang_page "ru" t :: !pages) site_pages_ru;

  (* Per-decision pages (English-only). *)
  List.iter
    (fun (decision_id, ob_html) ->
      let body = render_decision_page ~decision_id ~obligation_html:ob_html in
      pages :=
        {
          path = Filename.concat "decisions" (decision_id ^ ".html");
          body =
            render_page ~lang:"en" ~page_key:"packages"
              ~title:(Printf.sprintf "%s — math-coding" decision_id)
              ~body ~site_base:config.site_base
              ~enable_mathjax:config.enable_mathjax
              ~enable_mermaid:config.enable_mermaid
              ~enable_lang_toggle:config.enable_lang_toggle ~has_ru:false
              ~version ~extra_head:"";
        }
        :: !pages)
    decisions_data;

  (* Per-axiom pages (English-only — body content is the same). *)
  List.iter
    (fun (axiom_id, body_md) ->
      let body = render_axiom_page ~axiom_id ~body:body_md in
      pages :=
        {
          path = Filename.concat "axioms" (axiom_id ^ ".html");
          body =
            render_page ~lang:"en" ~page_key:"axioms"
              ~title:(Printf.sprintf "Axiom %s" axiom_id)
              ~body ~site_base:config.site_base
              ~enable_mathjax:config.enable_mathjax
              ~enable_mermaid:config.enable_mermaid
              ~enable_lang_toggle:config.enable_lang_toggle ~has_ru:false
              ~version ~extra_head:"";
        }
        :: !pages)
    axioms_data;

  (* Per-spec pages (English-only). The spec source under `spec/`
     is normative (algebra-3.2, constitution, domain, semantics);
     each page is forced to `enable_mathjax:true` regardless of
     `config.enable_mathjax` so MathJax 3 is always available for
     `$..$` / `$$..$$` formulas at runtime. Reading `spec/*.md`
     here — rather than in `bin/Mathc.ml` — keeps `lib/render.ml`
     self-contained: the spec surface lands under
     `dist/spec/<name>.html` whenever `mathc render` runs, without
     the dispatcher learning about spec pages. *)
  let spec_data = read_spec_files () in
  List.iter
    (fun (name, body_md) ->
      let body = render_spec_page ~name ~body_md in
      pages :=
        {
          path = Filename.concat "spec" (name ^ ".html");
          body =
            render_page ~lang:"en" ~page_key:("spec/" ^ name)
              ~title:(Printf.sprintf "%s — math-coding spec" name)
              ~body ~site_base:config.site_base ~enable_mathjax:true
              ~enable_mermaid:config.enable_mermaid
              ~enable_lang_toggle:config.enable_lang_toggle ~has_ru:false
              ~version ~extra_head:"";
        }
        :: !pages)
    spec_data;

  List.rev !pages

(* Default configuration used by the CLI. The dispatcher overrides
   from CLI flags. *)
let[@warning "-32"] default_config =
  {
    site_base = "/math-coding/";
    (* MathJax 3 is wired in the code path but defaults OFF. The
       `site/*.md` articles carry no `$...$` or `\[...\]` formulas;
       MathJax on every prose page aggressively typesets
       parenthetical English like `(Honest status)` as math italics
       (`<math>` tags wrap ordinary prose). The default-off keeps
       prose pages clean; the dispatcher opts pages in via the
       `--mathjax` flag or by setting
       `Render.config.enable_mathjax = true` programmatically.
       Spec pages (`spec/algebra-3.2.md`, `constitution.md`,
       `domain.md`, `semantics.md`) force `enable_mathjax:true`
       per-page inside `build_pages` regardless of this default —
       the normative spec is the only consumer that actually
       needs TeX typesetting. *)
    enable_mathjax = false;
    enable_mermaid = true;
    enable_lang_toggle = true;
    languages = [ "en" ];
    (* Default version reads from `./VERSION` at render time. The
       CLI dispatcher overrides this with whatever the current
       working directory's VERSION file holds, so a site deployed
       from a freshly-cut release tag carries the right version
       automatically. The string here is a last-resort fallback
       for callers that bypass the CLI. *)
    version = read_version_file ~fallback:default_version;
  }
