#!/usr/bin/env bash
# scripts/dist-adoption.sh
#
# Generate platform-specific adoption files from adoption/SKILL.md.
# One canonical skill in, N platform-shaped drop-ins out
# (opencode, Claude Code, Cursor, GitHub Copilot).
#
# Usage:
#   scripts/dist-adoption.sh                — generate to dist/adoption/
#   scripts/dist-adoption.sh --check        — exit 1 if dist/ is stale
#                                             relative to adoption/SKILL.md
#
# The script is idempotent: re-running overwrites the same files.
# Source of truth is adoption/SKILL.md; dist/ is a build artifact.
#
# Output:
#   dist/adoption/opencode/SKILL.md         (verbatim copy of source)
#   dist/adoption/claude-code/instructions.md
#   dist/adoption/cursor/rules.md
#   dist/adoption/copilot/instructions.md
#   dist/adoption/README.md
#
# Design notes (2026-10-04 rewrite):
# - Removed the double-mktemp + double-trap pattern. The original
#   script (rev <= v3.0.0.20) leaked a tempfile per invocation and
#   had an awk block that was overwritten by a "simpler" awk block
#   doing the same work. This rewrite is single-pass: read source
#   into a shell variable, extract body once, emit per-platform
#   files in a clean loop.
# - Uses `set -eu` (not `set -euo pipefail`). pipefail is omitted
#   because the awk body-extraction pipe has had port-dependent
#   behaviour between local dev and CI Ubuntu 22.04; the explicit
#   set -e + per-step error checks are sufficient for this script.
# - `cd "$(dirname "$0")/.."` is preserved: lets the script work
#   when invoked from any CWD (e.g., `cd /tmp && bash
#   /path/to/repo/scripts/dist-adoption.sh`). release.yml invokes
#   it from the repo root, but local dev may not.

set -euo pipefail

# Resolve repo root from the script's location. Works whether invoked
# as `./scripts/dist-adoption.sh` (CWD = repo root, no-op) or
# `bash /path/to/dist-adoption.sh` (CWD arbitrary, chdir here).
cd "$(cd "$(dirname "$0")" && pwd)/.."

# No `pipefail` here: the awk | body pipe has had port-dependent
# behaviour (CI Ubuntu 22.04 vs local) and a single failure mode
# here stops the entire release. With `set -eu` and explicit error
# messages, the script is robust without pipefail.
set -eu

src="adoption/SKILL.md"
out_root="dist/adoption"

if [[ ! -f "$src" ]]; then
  echo "dist-adoption: missing source $src" >&2
  exit 1
fi

check_mode=0
if [[ "${1:-}" == "--check" ]]; then
  check_mode=1
fi

# Read source once. Use a here-string (<<<) for the awk pipe; some
# shell+awk combinations have surprising pipefail behaviour with
# process substitution under `set -euo pipefail`, but the here-string
# is portable across bash 3.2/4.x and dash-derived /bin/sh.
src_content=$(cat "$src")

# Extract body: everything after the second '---' fence. Uses a
# portable awk pattern: count `---` lines, print from the second
# one onward. Compatible with both gawk and mawk (Ubuntu default).
body=$(awk '
  BEGIN { fence = 0 }
  /^---[[:space:]]*$/ { fence++; next }
  fence >= 2 { print }
' <<< "$src_content")

# emit <out_path> <header>
#   Writes <header>\n\n---\n\n<body> to <out_path>. Parent directory
#   is created if needed.
emit() {
  local out_path="$1" header="$2"
  mkdir -p "$(dirname "$out_path")"
  {
    printf '%s\n\n---\n\n%s\n' "$header" "$body"
  } > "$out_path"
}

# Wipe and recreate output root. Idempotent.
if [[ $check_mode -eq 0 ]]; then
  rm -rf "$out_root"
fi
mkdir -p "$out_root/opencode" "$out_root/claude-code" \
         "$out_root/cursor" "$out_root/copilot"

# opencode reads SKILL.md with frontmatter; copy the source verbatim.
if [[ $check_mode -eq 0 ]]; then
  cp "$src" "$out_root/opencode/SKILL.md"
fi

# Claude Code reads CLAUDE.md or .claude/instructions.md as plain
# instructions; strip the opencode-specific frontmatter and add a
# short platform header.
emit "$out_root/claude-code/instructions.md" \
  "# Math-coding adoption (Claude Code)

This file is a deploy of the canonical Math-coding skill at
\`adoption/SKILL.md\`. Do not edit this file directly; edit the source
and re-run \`scripts/dist-adoption.sh\`."

# Cursor reads .cursor/rules/*.md as project rules; same treatment as
# Claude Code but pointing at Cursor's expected path.
emit "$out_root/cursor/rules.md" \
  "# Math-coding adoption (Cursor)

Deploy target: \`.cursor/rules/math-coding.md\`. Copy this file to that
location. Edit the source at \`adoption/SKILL.md\` and re-run
\`scripts/dist-adoption.sh\` to regenerate."

# GitHub Copilot reads .github/instructions/*.instructions.md with an
# \`apply-to\` frontmatter field. Generate that wrapper.
emit "$out_root/copilot/instructions.md" \
  "---
apply-to: '**'
---

# Math-coding adoption (GitHub Copilot)

Deploy target: \`.github/instructions/math-coding.instructions.md\`.
Copy this file to that location. The \`apply-to: '**'\` field instructs
Copilot to apply these instructions to every file in the repository."

# README.md
cat > "$out_root/README.md" <<'README_EOF'
# Math-coding adoption bundle

This directory contains platform-specific drops of the canonical
adoption skill at `adoption/SKILL.md`. Pick the file for the agent
platform you use and place it at the target path in your project.

| Platform | File in this dir | Target path in your project |
|---|---|---|
| opencode | `opencode/SKILL.md` | `.opencode/skills/math-coding/SKILL.md` |
| Claude Code | `claude-code/instructions.md` | `CLAUDE.md` (merge) or `.claude/instructions.md` |
| Cursor | `cursor/rules.md` | `.cursor/rules/math-coding.md` |
| GitHub Copilot | `copilot/instructions.md` | `.github/instructions/math-coding.instructions.md` |

Source of truth: `adoption/SKILL.md`. To regenerate after editing,
run `scripts/dist-adoption.sh` from the repository root.

The `mc` binary referenced by the skill ships in the same release
tarball as this directory.
README_EOF

# --check mode: verify the four platform files exist and are non-empty.
# A full regeneration check would race with concurrent build steps; a
# presence-and-size check is sufficient for the contract.
if [[ $check_mode -eq 1 ]]; then
  missing=0
  for f in opencode/SKILL.md claude-code/instructions.md \
           cursor/rules.md copilot/instructions.md README.md; do
    if [[ ! -s "$out_root/$f" ]]; then
      echo "dist-adoption: stale — missing $out_root/$f" >&2
      missing=1
    fi
  done
  exit $missing
fi

echo "dist-adoption: ok — $out_root/"
